export const productBuckets = [
  // --- Cho productSpecId; 2 (Kích thước màn hình - Điện thoại, đơn vị ") ---
  {
    id: 1,
    productSpecId: 2,
    gt: null,
    lte: "6.1",
    label: '< 6.1"',
    sortOrder: 0,
  },
  {
    id: 2,
    productSpecId: 2,
    gt: "6.1",
    lte: "6.7",
    label: '6.1" - 6.7"',
    sortOrder: 1,
  },
  {
    id: 3,
    productSpecId: 2,
    gt: "6.7",
    lte: null,
    label: '> 6.7"',
    sortOrder: 2,
  },

  // --- Cho productSpecId; 4 (Tần số quét - Điện thoại, đơn vị Hz) ---
  {
    id: 4,
    productSpecId: 4,
    gt: null,
    lte: "60",
    label: "< 60Hz",
    sortOrder: 0,
  },
  {
    id: 5,
    productSpecId: 4,
    gt: "60",
    lte: "90",
    label: "60-90Hz",
    sortOrder: 1,
  },
  {
    id: 6,
    productSpecId: 4,
    gt: "90",
    lte: "120",
    label: "90-120Hz",
    sortOrder: 2,
  },
  {
    id: 7,
    productSpecId: 4,
    gt: "120",
    lte: null,
    label: "> 120Hz",
    sortOrder: 3,
  },

  // --- Cho productSpecId; 6 (RAM - Điện thoại, đơn vị GB) ---
  { id: 8, productSpecId: 7, gt: null, lte: "6", label: "< 6GB", sortOrder: 0 },
  { id: 9, productSpecId: 7, gt: "6", lte: "8", label: "6-8GB", sortOrder: 1 },
  {
    id: 10,
    productSpecId: 7,
    gt: "8",
    lte: "12",
    label: "8-12GB",
    sortOrder: 2,
  },
  {
    id: 11,
    productSpecId: 7,
    gt: "12",
    lte: null,
    label: "> 12GB",
    sortOrder: 3,
  },

  // --- Cho productSpecId; 8 (Dung lượng pin - Điện thoại, đơn vị mAh) ---
  {
    id: 12,
    productSpecId: 8,
    gt: null,
    lte: "4000",
    label: "< 4000mAh",
    sortOrder: 0,
  },
  {
    id: 13,
    productSpecId: 8,
    gt: "4000",
    lte: "5000",
    label: "4000-5000mAh",
    sortOrder: 1,
  },
  {
    id: 14,
    productSpecId: 8,
    gt: "5000",
    lte: null,
    label: "> 5000mAh",
    sortOrder: 2,
  },

  // --- Cho productSpecId; 9 (Camera sau - Điện thoại, đơn vị MP) ---
  {
    id: 15,
    productSpecId: 9,
    gt: null,
    lte: "48",
    label: "< 48MP",
    sortOrder: 0,
  },
  {
    id: 16,
    productSpecId: 9,
    gt: "48",
    lte: "64",
    label: "48-64MP",
    sortOrder: 1,
  },
  {
    id: 17,
    productSpecId: 9,
    gt: "64",
    lte: "108",
    label: "64-108MP",
    sortOrder: 2,
  },
  {
    id: 18,
    productSpecId: 9,
    gt: "108",
    lte: null,
    label: "> 108MP",
    sortOrder: 3,
  },

  // --- Cho productSpecId; 18 (Kích thước màn hình - Laptop, đơn vị ") ---
  {
    id: 19,
    productSpecId: 15,
    gt: null,
    lte: "13",
    label: '< 13"',
    sortOrder: 0,
  },
  {
    id: 20,
    productSpecId: 15,
    gt: "13",
    lte: "14",
    label: '13"-14"',
    sortOrder: 1,
  },
  {
    id: 21,
    productSpecId: 15,
    gt: "14",
    lte: "15",
    label: '14" - 15"',
    sortOrder: 2,
  },
  {
    id: 22,
    productSpecId: 15,
    gt: "15",
    lte: null,
    label: '> 15"',
    sortOrder: 3,
  },
];
