export const productSpecs = [
  {
    id: 1,
    specTemplateId: 1,
    code: "os",
    label: "Hệ điều hành",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Cấu hình",
    displayOrder: 1,
  },
  {
    id: 2,
    specTemplateId: 1,
    code: "screen_size",
    label: "Kích thước màn hình",
    valueType: "range",
    datatype: "number",
    unit: "inch",
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 2,
  },
  {
    id: 3,
    specTemplateId: 1,
    code: "screen_tech",
    label: "Công nghệ màn hình",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 3,
  },
  {
    id: 4,
    specTemplateId: 1,
    code: "refresh_rate",
    label: "Tần số quét",
    valueType: "range",
    datatype: "number",
    unit: "Hz",
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 4,
  },
  {
    id: 5,
    specTemplateId: 1,
    code: "cpu_model",
    label: "Chip xử lý",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Hiệu năng",
    displayOrder: 5,
  },
  {
    id: 6,
    specTemplateId: 1,
    code: "chipset",
    label: "Chipset",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: false,
    control: "select",
    isRequired: false,
    groupLabel: "Hiệu năng",
    displayOrder: 6,
  },
  {
    id: 7,
    specTemplateId: 1,
    code: "ram",
    label: "RAM",
    valueType: "range",
    datatype: "number",
    unit: "GB",
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Hiệu năng",
    displayOrder: 6,
  },
  {
    id: 8,
    specTemplateId: 1,
    code: "battery",
    label: "Dung lượng pin",
    valueType: "range",
    datatype: "number",
    unit: "mAh",
    filterable: true,
    control: "multiselect",
    isRequired: true,
    groupLabel: "Pin & Sạc",
    displayOrder: 7,
  },
  {
    id: 9,
    specTemplateId: 1,
    code: "rear_camera_mp",
    label: "Camera sau",
    valueType: "range",
    datatype: "number",
    unit: "MP",
    filterable: false,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Camera",
    displayOrder: 8,
  },
  {
    id: 10,
    specTemplateId: 1,
    code: "nfc",
    label: "Công nghệ NFC",
    valueType: "discrete",
    datatype: "boolean",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: null,
    displayOrder: 9,
  },

  {
    id: 11,
    specTemplateId: 2,
    code: "os",
    label: "Hệ điều hành",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Hệ điều hành",
    displayOrder: 1,
  },
  {
    id: 12,
    specTemplateId: 2,
    code: "cpu_model",
    label: "CPU",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "CPU",
    displayOrder: 2,
  },
  {
    id: 13,
    specTemplateId: 2,
    code: "storage_type",
    label: "Chuẩn lưu trữ",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Bộ nhớ",
    displayOrder: 3,
  },
  {
    id: 14,
    specTemplateId: 2,
    code: "gpu_model",
    label: "Model GPU",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: false,
    control: "select",
    isRequired: false,
    groupLabel: "Đồ họa",
    displayOrder: 4,
  },
  {
    id: 15,
    specTemplateId: 2,
    code: "screen_size",
    label: "Kích thước màn hình",
    valueType: "range",
    datatype: "number",
    unit: "inch",
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 5,
  },
  {
    id: 16,
    specTemplateId: 3,
    code: "micro",
    label: "Micro",
    valueType: "discrete",
    datatype: "boolean",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: null,
    displayOrder: 1,
  },
  {
    id: 17,
    specTemplateId: 3,
    code: "battery_life",
    label: "Thời lượng pin",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: false,
    control: "select",
    isRequired: false,
    groupLabel: null,
    displayOrder: 2,
  },
  {
    id: 18,
    specTemplateId: 4,
    code: "battery",
    label: "Dung lượng pin",
    valueType: "discrete",
    datatype: "number",
    unit: "mAh",
    filterable: false,
    control: "select",
    isRequired: false,
    groupLabel: null,
    displayOrder: 1,
  },
  {
    id: 19,
    specTemplateId: 4,
    code: "input-port",
    label: "Cổng sạc vào",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: false,
    control: "select",
    isRequired: false,
    groupLabel: null,
    displayOrder: 2,
  },
  {
    id: 20,
    specTemplateId: 4,
    code: "output-port",
    label: "Cổng sạc ra",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: false,
    control: "select",
    isRequired: false,
    groupLabel: null,
    displayOrder: 3,
  },
];
