// constants/permissions.js

// Chỉ cần key, không cần id/description
export const PERMISSION_KEYS = {
  // STAFF & ROLE
  VIEW_STAFF: "VIEW_STAFF",
  CREATE_STAFF: "CREATE_STAFF",
  UPDATE_STAFF: "UPDATE_STAFF",
  DELETE_STAFF: "DELETE_STAFF",

  VIEW_ROLE: "VIEW_ROLE",
  CREATE_ROLE: "CREATE_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  ASSIGN_ROLE: "ASSIGN_ROLE",

  // CUSTOMER
  VIEW_CUSTOMER: "VIEW_CUSTOMER",
  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",

  // PRODUCT & VARIANT
  VIEW_PRODUCT: "VIEW_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",

  VIEW_VARIANT: "VIEW_VARIANT",
  CREATE_VARIANT: "CREATE_VARIANT",
  UPDATE_VARIANT: "UPDATE_VARIANT",
  DELETE_VARIANT: "DELETE_VARIANT",

  // ORDER & RMA
  VIEW_ORDER: "VIEW_ORDER",
  CREATE_ORDER: "CREATE_ORDER",
  DELETE_ORDER: "DELETE_ORDER",
  UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",
  VIEW_RMA: "VIEW_RMA",
  PROCESS_RMA: "PROCESS_RMA",

  // PAYMENT
  VIEW_PAYMENT_METHOD: "VIEW_PAYMENT_METHOD",
  CREATE_PAYMENT_METHOD: "CREATE_PAYMENT_METHOD",
  UPDATE_PAYMENT_METHOD: "UPDATE_PAYMENT_METHOD",
  DELETE_PAYMENT_METHOD: "DELETE_PAYMENT_METHOD",
  VIEW_PAYMENT_TRANSACTION: "VIEW_PAYMENT_TRANSACTION",

  // COUPON
  VIEW_COUPON: "VIEW_COUPON",
  CREATE_COUPON: "CREATE_COUPON",
  UPDATE_COUPON: "UPDATE_COUPON",
  DELETE_COUPON: "DELETE_COUPON",

  // INVENTORY & DEVICE
  VIEW_INVENTORY: "VIEW_INVENTORY",
  MANAGE_INVENTORY: "MANAGE_INVENTORY",
  VIEW_DEVICE: "VIEW_DEVICE",
  MANAGE_DEVICE: "MANAGE_DEVICE",

  // REVIEW & BANNER
  VIEW_REVIEW: "VIEW_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW",

  VIEW_BANNER: "VIEW_BANNER",
  CREATE_BANNER: "CREATE_BANNER",
  UPDATE_BANNER: "UPDATE_BANNER",
  DELETE_BANNER: "DELETE_BANNER",

  // CATEGORY
  VIEW_CATEGORY: "VIEW_CATEGORY",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  // BRAND
  VIEW_BRAND: "VIEW_BRAND",
  CREATE_BRAND: "CREATE_BRAND",
  UPDATE_BRAND: "UPDATE_BRAND",
  DELETE_BRAND: "DELETE_BRAND",

  CREATE_PAYMENT_ACCOUNT: "CREATE_PAYMENT_ACCOUNT",
  UPDATE_PAYMENT_ACCOUNT: "UPDATE_PAYMENT_ACCOUNT",
  DELETE_PAYMENT_ACCOUNT: "DELETE_PAYMENT_ACCOUNT",

  VIEW_REPORT: "VIEW_REPORT",
  UPDATE_REVIEW: "UPDATE_REVIEW",

  VIEW_SPEC: "VIEW_SPEC",
  UPDATE_SPEC: "UPDATE_SPEC",
  DELETE_SPEC: "DELETE_SPEC",
  CREATE_SPEC: "CREATE_SPEC",
};
