import { ControlType, DataType, Prisma, ValueType } from "@prisma/client";

// ---------------------------
// 1. DỮ LIỆU DANH MỤC (CATEGORIES)
// ---------------------------
export const categories: Prisma.CategoryCreateInput[] = [
  {
    name: "Điện thoại",
    slug: "dien-thoai",
  },
  {
    name: "Laptop",
    slug: "laptop",
  },
];

// ---------------------------
// 2. DỮ LIỆU THƯƠNG HIỆU (BRANDS)
// ---------------------------
export const brands: Prisma.BrandCreateInput[] = [
  // Điện thoại & Laptop
  {
    name: "Apple",
    slug: "apple",
  },
  {
    name: "Huawei",
    slug: "huawei",
  },
  {
    name: "Vivo",
    slug: "vivo",
  },
  {
    name: "Dell",
    slug: "dell",
  },
  {
    name: "Acer",
    slug: "acer",
  },
  {
    name: "HP",
    slug: "hp",
  },
  {
    name: "Samsung",
    slug: "samsung",
  },
  {
    name: "Realme",
    slug: "realme",
  },
  {
    name: "ASUS",
    slug: "asus",
  },
  {
    name: "MSI",
    slug: "msi",
  },
  {
    name: "Lenovo",
    slug: "lenovo",
  },
  {
    name: "Xiaomi",
    slug: "xiaomi",
  },
  {
    name: "Nokia",
    slug: "nokia",
  },
  {
    name: "OPPO",
    slug: "oppo",
  },
];

// ---------------------------
// 3. DỮ LIỆU TEMPLATE THÔNG SỐ (SPEC TEMPLATES)
// ---------------------------
export const specTemplates: Prisma.SpecTemplateCreateInput[] = [
  {
    name: "Điện thoại - V1",
    version: 1,
    isActive: true,
    category: {
      connect: {
        slug: "dien-thoai",
      },
    },
  },
  {
    name: "Laptop - V1",
    version: 1,
    isActive: true,
    category: {
      connect: {
        slug: "laptop",
      },
    },
  },
];

// Định nghĩa kiểu dữ liệu đơn giản hóa cho việc tạo ProductSpec bằng ID trực tiếp
interface ProductSpecSeedInput {
  specTemplateId: number;
  code: string;
  label: string;
  valueType: ValueType;
  datatype: DataType;
  unit: string | null;
  filterable: boolean;
  control: ControlType;
  isRequired: boolean;
  groupLabel: string | null;
  displayOrder: number;
}

// =================================================================
// 4. DỮ LIỆU THÔNG SỐ SẢN PHẨM (PRODUCT SPECS)
// CHÚ Ý: Đã loại bỏ trường 'id' và dùng 'specTemplateId' trực tiếp.
// =================================================================
export const productSpecs: ProductSpecSeedInput[] = [
  // --- Specs cho SpecTemplate ID: 1 (Điện thoại - V1) ---
  {
    specTemplateId: 1,
    code: "os",
    label: "Hệ điều hành",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Cấu hình",
    displayOrder: 1,
  },
  {
    specTemplateId: 1,
    code: "screen_size",
    label: "Kích thước màn hình",
    valueType: "range",
    datatype: "number",
    unit: "inch",
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 2,
  },
  {
    specTemplateId: 1,
    code: "screen_tech",
    label: "Công nghệ màn hình",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 3,
  },
  {
    specTemplateId: 1,
    code: "refresh_rate",
    label: "Tần số quét",
    valueType: "range",
    datatype: "number",
    unit: "Hz",
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 4,
  },
  {
    specTemplateId: 1,
    code: "cpu_model",
    label: "Chip xử lý",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Hiệu năng",
    displayOrder: 5,
  },
  {
    specTemplateId: 1,
    code: "ram",
    label: "RAM",
    valueType: "range",
    datatype: "number",
    unit: "GB",
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Hiệu năng",
    displayOrder: 6,
  },
  {
    specTemplateId: 1,
    code: "battery",
    label: "Dung lượng pin",
    valueType: "range",
    datatype: "number",
    unit: "mAh",
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Pin & Sạc",
    displayOrder: 8,
  },
  {
    specTemplateId: 1,
    code: "rear_camera_mp",
    label: "Camera sau",
    valueType: "range",
    datatype: "number",
    unit: "MP",
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Camera",
    displayOrder: 9,
  },

  // --- Specs cho SpecTemplate ID: 2 (Laptop - V1) ---
  {
    specTemplateId: 2,
    code: "os",
    label: "Hệ điều hành",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Hệ điều hành",
    displayOrder: 1,
  },
  {
    specTemplateId: 2,
    code: "cpu_model",
    label: "CPU",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "CPU",
    displayOrder: 3,
  },
  {
    specTemplateId: 2,
    code: "storage_type",
    label: "Chuẩn lưu trữ",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Bộ nhớ",
    displayOrder: 6,
  },
  {
    specTemplateId: 2,
    code: "gpu_model",
    label: "Model GPU",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Đồ họa",
    displayOrder: 8,
  },
  {
    specTemplateId: 2,
    code: "screen_size",
    label: "Kích thước màn hình",
    valueType: "range",
    datatype: "number",
    unit: "inch",
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 9,
  },
];

// Định nghĩa kiểu dữ liệu đơn giản hóa cho ProductSpecOption
interface ProductSpecOptionSeedInput {
  productSpecId: number;
  value: string;
  label: string;
  sortOrder: number;
}

// =================================================================
// 5. DỮ LIỆU TÙY CHỌN THÔNG SỐ (PRODUCT SPEC OPTIONS)
// CHÚ Ý: Đã loại bỏ trường 'id' và dùng 'productSpecId' trực tiếp.
// =================================================================
export const productSpecOptions: ProductSpecOptionSeedInput[] = [
  // --- Cho productSpecId: 1 (Hệ điều hành - Điện thoại) ---
  { productSpecId: 1, value: "Android", label: "Android", sortOrder: 0 },
  { productSpecId: 1, value: "iOS", label: "iOS", sortOrder: 1 },

  // --- Cho productSpecId: 3 (Công nghệ màn hình) ---
  { productSpecId: 3, value: "AMOLED", label: "AMOLED", sortOrder: 0 },
  { productSpecId: 3, value: "OLED", label: "OLED", sortOrder: 1 },
  { productSpecId: 3, value: "IPS", label: "IPS", sortOrder: 2 },
  { productSpecId: 3, value: "LTPO", label: "LTPO", sortOrder: 3 },

  // --- Cho productSpecId: 4 (Tần số quét) ---
  { productSpecId: 4, value: "60", label: "60Hz", sortOrder: 0 },
  { productSpecId: 4, value: "90", label: "90Hz", sortOrder: 1 },
  { productSpecId: 4, value: "120", label: "120Hz", sortOrder: 2 },
  { productSpecId: 4, value: "144", label: "144Hz", sortOrder: 3 },

  // --- Cho productSpecId: 5 (Chip xử lý - Điện thoại) ---
  { productSpecId: 5, value: "Apple A", label: "Apple A", sortOrder: 0 },
  { productSpecId: 5, value: "Snapdragon", label: "Snapdragon", sortOrder: 1 },
  { productSpecId: 5, value: "Dimensity", label: "Dimensity", sortOrder: 2 },
  { productSpecId: 5, value: "Exynos", label: "Exynos", sortOrder: 3 },

  // --- Cho productSpecId: 6 (RAM - Điện thoại) ---
  { productSpecId: 6, value: "4", label: "4GB", sortOrder: 0 },
  { productSpecId: 6, value: "6", label: "6GB", sortOrder: 1 },
  { productSpecId: 6, value: "8", label: "8GB", sortOrder: 2 },
  { productSpecId: 6, value: "12", label: "12GB", sortOrder: 3 },
  { productSpecId: 6, value: "16", label: "16GB", sortOrder: 4 },

  // --- Cho productSpecId: 10 (Hệ điều hành - Laptop) ---
  { productSpecId: 10, value: "Windows", label: "Windows", sortOrder: 0 },
  { productSpecId: 10, value: "macOS", label: "macOS", sortOrder: 1 },
  { productSpecId: 10, value: "Linux", label: "Linux", sortOrder: 2 },

  // --- Cho productSpecId: 12 (CPU - Laptop) ---
  { productSpecId: 12, value: "Core i5", label: "Intel Core i5", sortOrder: 0 },
  { productSpecId: 12, value: "Core i7", label: "Intel Core i7", sortOrder: 1 },
  { productSpecId: 12, value: "Ryzen 5", label: "AMD Ryzen 5", sortOrder: 2 },
  { productSpecId: 12, value: "Ryzen 7", label: "AMD Ryzen 7", sortOrder: 3 },
  { productSpecId: 12, value: "M2", label: "Apple M2", sortOrder: 4 },
  { productSpecId: 12, value: "M3", label: "Apple M3", sortOrder: 5 },

  // --- Cho productSpecId: 15 (Chuẩn lưu trữ) ---
  { productSpecId: 15, value: "SSD", label: "SSD", sortOrder: 0 },
  { productSpecId: 15, value: "HDD", label: "HDD", sortOrder: 1 },

  // --- Cho productSpecId: 17 (Model GPU) ---
  {
    productSpecId: 17,
    value: "Intel Iris Xe",
    label: "Intel Iris Xe",
    sortOrder: 0,
  },
  {
    productSpecId: 17,
    value: "RTX 3050",
    label: "NVIDIA RTX 3050",
    sortOrder: 1,
  },
  {
    productSpecId: 17,
    value: "RTX 4050",
    label: "NVIDIA RTX 4050",
    sortOrder: 2,
  },
  {
    productSpecId: 17,
    value: "Radeon 780M",
    label: "AMD Radeon 780M",
    sortOrder: 3,
  },
];

// Định nghĩa kiểu dữ liệu đơn giản hóa cho ProductBucket
interface ProductBucketSeedInput {
  productSpecId: number;
  gt: string | null; // Sử dụng string hoặc null để seed giá trị Decimal
  lte: string | null; // Sử dụng string hoặc null để seed giá trị Decimal
  label: string;
  sortOrder: number;
}

// =================================================================
// 6. DỮ LIỆU KHOẢNG GIÁ TRỊ (PRODUCT BUCKETS)
// =================================================================
export const productBuckets: ProductBucketSeedInput[] = [
  // --- Cho productSpecId: 2 (Kích thước màn hình - Điện thoại, đơn vị ") ---
  {
    productSpecId: 2,
    gt: null,
    lte: "6.1",
    label: '< 6.1"',
    sortOrder: 0,
  },
  {
    productSpecId: 2,
    gt: "6.1",
    lte: "6.7",
    label: '6.1" - 6.7"',
    sortOrder: 1,
  },
  {
    productSpecId: 2,
    gt: "6.7",
    lte: null,
    label: '> 6.7"',
    sortOrder: 2,
  },

  // --- Cho productSpecId: 4 (Tần số quét - Điện thoại, đơn vị Hz) ---
  {
    productSpecId: 4,
    gt: null,
    lte: "60",
    label: "< 60Hz",
    sortOrder: 0,
  },
  {
    productSpecId: 4,
    gt: "60",
    lte: "90",
    label: "60–90Hz",
    sortOrder: 1,
  },
  {
    productSpecId: 4,
    gt: "90",
    lte: "120",
    label: "90–120Hz",
    sortOrder: 2,
  },
  {
    productSpecId: 4,
    gt: "120",
    lte: null,
    label: "> 120Hz",
    sortOrder: 3,
  },

  // --- Cho productSpecId: 6 (RAM - Điện thoại, đơn vị GB) ---
  {
    productSpecId: 6,
    gt: null,
    lte: "6",
    label: "< 6GB",
    sortOrder: 0,
  },
  {
    productSpecId: 6,
    gt: "6",
    lte: "8",
    label: "6–8GB",
    sortOrder: 1,
  },
  {
    productSpecId: 6,
    gt: "8",
    lte: "12",
    label: "8–12GB",
    sortOrder: 2,
  },
  {
    productSpecId: 6,
    gt: "12",
    lte: null,
    label: "> 12GB",
    sortOrder: 3,
  },

  // --- Cho productSpecId: 8 (Dung lượng pin - Điện thoại, đơn vị mAh) ---
  {
    productSpecId: 8,
    gt: null,
    lte: "4000",
    label: "< 4000mAh",
    sortOrder: 0,
  },
  {
    productSpecId: 8,
    gt: "4000",
    lte: "5000",
    label: "4000–5000mAh",
    sortOrder: 1,
  },
  {
    productSpecId: 8,
    gt: "5000",
    lte: null,
    label: "> 5000mAh",
    sortOrder: 2,
  },

  // --- Cho productSpecId: 9 (Camera sau - Điện thoại, đơn vị MP) ---
  {
    productSpecId: 9,
    gt: null,
    lte: "48",
    label: "< 48MP",
    sortOrder: 0,
  },
  {
    productSpecId: 9,
    gt: "48",
    lte: "64",
    label: "48–64MP",
    sortOrder: 1,
  },
  {
    productSpecId: 9,
    gt: "64",
    lte: "108",
    label: "64–108MP",
    sortOrder: 2,
  },
  {
    productSpecId: 9,
    gt: "108",
    lte: null,
    label: "> 108MP",
    sortOrder: 3,
  },

  // --- Cho productSpecId: 18 (Kích thước màn hình - Laptop, đơn vị ") ---
  {
    productSpecId: 18,
    gt: null,
    lte: "13",
    label: '< 13"',
    sortOrder: 0,
  },
  {
    productSpecId: 18,
    gt: "13",
    lte: "14",
    label: '13"–14"',
    sortOrder: 1,
  },
  {
    productSpecId: 18,
    gt: "14",
    lte: "15",
    label: '14" - 15"',
    sortOrder: 2,
  },
  {
    productSpecId: 18,
    gt: "15",
    lte: null,
    label: '> 15"',
    sortOrder: 3,
  },
];

interface VariantSpecSeedInput {
  specTemplateId: number;
  code: string;
  label: string;
  valueType: ValueType;
  datatype: DataType;
  unit: string | null;
  filterable: boolean;
  control: ControlType;
  isRequired: boolean;
  isVariantKey: boolean;
  orderIndex: number;
  groupLabel: string | null;
  displayOrder: number;
}

interface VariantSpecOptionSeedInput {
  variantSpecId: number;
  value: string;
  label: string;
  sortOrder: number;
}

// =================================================================
// 2. DỮ LIỆU THÔNG SỐ BIẾN THỂ (VARIANT SPECS)
// =================================================================
export const variantSpecs: VariantSpecSeedInput[] = [
  // specTemplateId: 1 (Điện thoại)
  {
    specTemplateId: 1,
    code: "storage_variant",
    label: "Dung lượng lưu trữ",
    valueType: ValueType.range,
    datatype: DataType.number,
    unit: "GB",
    filterable: true,
    control: ControlType.multiselect,
    isRequired: false,
    isVariantKey: true,
    orderIndex: 2,
    groupLabel: null,
    displayOrder: 2,
  },

  // specTemplateId: 2 (Laptop)
  {
    specTemplateId: 2,
    code: "ram_variant",
    label: "RAM",
    valueType: ValueType.discrete,
    datatype: DataType.number,
    unit: "GB",
    filterable: true,
    control: ControlType.select,
    isRequired: false,
    isVariantKey: true,
    orderIndex: 2,
    groupLabel: null,
    displayOrder: 2,
  },
  {
    specTemplateId: 2,
    code: "storage_variant",
    label: "Dung lượng lưu trữ",
    valueType: ValueType.range,
    datatype: DataType.number,
    unit: "GB",
    filterable: true,
    control: ControlType.multiselect,
    isRequired: false,
    isVariantKey: true,
    orderIndex: 3,
    groupLabel: null,
    displayOrder: 3,
  },
];

// =================================================================
// 3. DỮ LIỆU TÙY CHỌN THÔNG SỐ BIẾN THỂ (VARIANT SPEC OPTIONS)
// =================================================================
export const variantSpecOptions: VariantSpecOptionSeedInput[] = [
  // Dựa trên variantSpecId: 4
  { variantSpecId: 2, value: "8", label: "8GB", sortOrder: 0 },
  { variantSpecId: 2, value: "16", label: "16GB", sortOrder: 1 },
  { variantSpecId: 2, value: "32", label: "32GB", sortOrder: 2 },
];

// Định nghĩa kiểu dữ liệu đơn giản hóa cho VariantBucket
interface VariantBucketSeedInput {
  variantSpecId: number;
  gt: string | null; // Sử dụng string hoặc null
  lte: string | null; // Sử dụng string hoặc null
  label: string;
  sortOrder: number;
}

// =================================================================
// 8. DỮ LIỆU KHOẢNG GIÁ TRỊ BIẾN THỂ (VARIANT BUCKETS)
// CHÚ Ý: DÙNG ID CỨNG (variantSpecId: 2 và 5)
// =================================================================
export const variantBuckets: VariantBucketSeedInput[] = [
  // --- Cho variantSpecId: 2 (storage_variant của Điện thoại - Giả định) ---
  {
    variantSpecId: 1,
    gt: null,
    lte: "128",
    label: "< 128GB",
    sortOrder: 0,
  },
  {
    variantSpecId: 1,
    gt: "128",
    lte: "256",
    label: "128GB - 256GB",
    sortOrder: 1,
  },
  {
    variantSpecId: 1,
    gt: "256",
    lte: "512",
    label: "256GB - 512GB",
    sortOrder: 2,
  },
  {
    variantSpecId: 1,
    gt: "512",
    lte: null,
    label: "> 512GB",
    sortOrder: 3,
  },

  // --- Cho variantSpecId: 5 (storage_variant của Laptop - Giả định) ---
  {
    variantSpecId: 3,
    gt: null,
    lte: "512",
    label: "< 512GB",
    sortOrder: 0,
  },
  {
    variantSpecId: 3,
    gt: "512",
    lte: "1024",
    label: "512GB - 1TB",
    sortOrder: 1,
  },
  {
    variantSpecId: 3,
    gt: "1024",
    lte: null,
    label: "> 1TB",
    sortOrder: 2,
  },
];

// Định nghĩa kiểu dữ liệu cho việc tạo Product
// Loại bỏ 'id' và 'createdAt' vì DB sẽ tự quản lý
interface ProductSeedInput {
  name: string;
  slug: string;
  brandId: number;
  categoryId: number;
  description: string;
  ratingAvg?: number;
  ratingCount?: number;
  isActive?: boolean;
}

// Dữ liệu Product bạn đã cung cấp
const productsToCreate: ProductSeedInput[] = [
  {
    name: "Laptop Small Rubber Fish 1",
    slug: "laptop-small-rubber-fish-1",
    brandId: 6,
    categoryId: 2,
    description:
      "Our zesty-inspired Pizza brings a taste of luxury to your monstrous lifestyle",
  },
  {
    name: "Laptop Tasty Rubber Fish 2",
    slug: "laptop-tasty-rubber-fish-2",
    brandId: 6,
    categoryId: 2,
    description:
      "Professional-grade Salad perfect for all training and recreational use",
  },
  {
    name: "Laptop Handcrafted Marble Sausages 3",
    slug: "laptop-handcrafted-marble-sausages-3",
    brandId: 7,
    categoryId: 2,
    description: "New gold Pants with ergonomic design for flowery comfort",
  },
  {
    name: "Laptop Ergonomic Bronze Shoes 4",
    slug: "laptop-ergonomic-bronze-shoes-4",
    brandId: 2,
    categoryId: 2,
    description:
      "Our cow-friendly Salad ensures mediocre comfort for your pets",
  },
  {
    name: "Laptop Bespoke Bronze Bacon 5",
    slug: "laptop-bespoke-bronze-bacon-5",
    brandId: 13,
    categoryId: 2,
    description:
      "The silver Gloves combines Guernsey aesthetics with Hydrogen-based durability",
  },
  {
    name: "Laptop Practical Cotton Sausages 6",
    slug: "laptop-practical-cotton-sausages-6",
    brandId: 6,
    categoryId: 2,
    description: "Ergonomic Bacon made with Marble for all-day frizzy support",
  },
  {
    name: "Laptop Rustic Gold Pizza 7",
    slug: "laptop-rustic-gold-pizza-7",
    brandId: 10,
    categoryId: 2,
    description:
      "Our zebra-friendly Chair ensures different comfort for your pets",
  },
  {
    name: "Laptop Unbranded Marble Computer 8",
    slug: "laptop-unbranded-marble-computer-8",
    brandId: 5,
    categoryId: 2,
    description: "Ergonomic Hat made with Metal for all-day front support",
  },
  {
    name: "Laptop Oriental Bronze Cheese 9",
    slug: "laptop-oriental-bronze-cheese-9",
    brandId: 3,
    categoryId: 2,
    description:
      "Experience the orchid brilliance of our Soap, perfect for selfish environments",
  },
  {
    name: "Laptop Tasty Wooden Bike 10",
    slug: "laptop-tasty-wooden-bike-10",
    brandId: 11,
    categoryId: 2,
    description:
      "Our flamingo-friendly Shoes ensures ultimate comfort for your pets",
  },
  {
    name: "Điện thoại Sleek Rubber Bacon 1",
    slug: "dien-thoai-sleek-rubber-bacon-1",
    brandId: 8,
    categoryId: 1,
    description:
      "Ergonomic Cheese made with Marble for all-day forsaken support",
  },
  {
    name: "Điện thoại Bespoke Steel Soap 2",
    slug: "dien-thoai-bespoke-steel-soap-2",
    brandId: 2,
    categoryId: 1,
    description:
      "The sleek and adolescent Bacon comes with indigo LED lighting for smart functionality",
  },
  {
    name: "Điện thoại Small Concrete Pizza 3",
    slug: "dien-thoai-small-concrete-pizza-3",
    brandId: 5,
    categoryId: 1,
    description:
      "Our bitter-inspired Keyboard brings a taste of luxury to your brave lifestyle",
  },
  {
    name: "Điện thoại Refined Cotton Keyboard 4",
    slug: "dien-thoai-refined-cotton-keyboard-4",
    brandId: 8,
    categoryId: 1,
    description:
      "The Fully-configurable optimizing capability Car offers reliable performance and warped design",
  },
  {
    name: "Điện thoại Tasty Steel Bacon 5",
    slug: "dien-thoai-tasty-steel-bacon-5",
    brandId: 6,
    categoryId: 1,
    description:
      "Experience the magenta brilliance of our Chicken, perfect for ordinary environments",
  },
  {
    name: "Điện thoại Tasty Silk Soap 6",
    slug: "dien-thoai-tasty-silk-soap-6",
    brandId: 11,
    categoryId: 1,
    description:
      "Introducing the United Arab Emirates-inspired Cheese, blending different style with local craftsmanship",
  },
  {
    name: "Điện thoại Modern Ceramic Pants 7",
    slug: "dien-thoai-modern-ceramic-pants-7",
    brandId: 3,
    categoryId: 1,
    description: "Ergonomic Ball made with Gold for all-day reflecting support",
  },
  {
    name: "Điện thoại Incredible Gold Soap 8",
    slug: "dien-thoai-incredible-gold-soap-8",
    brandId: 6,
    categoryId: 1,
    description:
      "Discover the lumbering new Table with an exciting mix of Aluminum ingredients",
  },
  {
    name: "Điện thoại Licensed Granite Pizza 9",
    slug: "dien-thoai-licensed-granite-pizza-9",
    brandId: 7,
    categoryId: 1,
    description:
      "The Polarised heuristic migration Tuna offers reliable performance and rubbery design",
  },
  {
    name: "Điện thoại Gorgeous Gold Sausages 10",
    slug: "dien-thoai-gorgeous-gold-sausages-10",
    brandId: 14,
    categoryId: 1,
    description:
      "Stylish Shoes designed to make you stand out with extra-large looks",
  },
];

// Định nghĩa kiểu dữ liệu cho việc tạo ProductSpecValue
// Đã loại bỏ 'id' và 'valueJson'
interface ProductSpecValueSeedInput {
  productId: number;
  specKey: string;
  label: string | null;
  type: DataType;
  unit: string | null;
  stringValue: string | null;
  numericValue: number | null;
  booleanValue: boolean | null;
}

// Map để chuyển từ specKey sang label tiếng Việt theo yêu cầu
const specKeyToLabelMap: Record<string, string> = {
  os: "Hệ điều hành",
  cpu_model: "Chip xử lý",
  storage_type: "Chuẩn lưu trữ",
  gpu_model: "Model GPU",
  screen_size: "Kích thước màn hình",
  screen_tech: "Công nghệ màn hình",
  refresh_rate: "Tần số quét",
  ram: "RAM",
  battery: "Dung lượng pin",
  rear_camera_mp: "Camera sau",
};

// Dữ liệu đã được xử lý và làm sạch
const productSpecValuesToCreate: ProductSpecValueSeedInput[] = [
  {
    productId: 1,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Linux",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Core i5",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "HDD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Radeon 780M",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 15.6,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Linux",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "M2",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Radeon 780M",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 12.9,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "macOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Core i5",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Radeon 780M",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 14,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "M2",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "HDD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Radeon 780M",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 13.5,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "macOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "M2",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "RTX 4050",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 15,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Linux",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "M2",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "HDD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Radeon 780M",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 14,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Linux",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Core i5",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "HDD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Iris Xe",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 14.5,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Linux",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Ryzen 5",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "HDD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Iris Xe",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Linux",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Ryzen 7",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Radeon 780M",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 12.5,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Core i5",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Radeon 780M",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 17,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "iOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.8,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 60,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 3900,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 108,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "iOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.1,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "LTPO",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 60,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4500,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 48,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "iOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.0,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "LTPO",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 60,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5100,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 200,
    booleanValue: null,
  },
  {
    productId: 14,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "iOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 14,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 5.9,
    booleanValue: null,
  },
  {
    productId: 14,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "OLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 14,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 60,
    booleanValue: null,
  },
  {
    productId: 14,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Exynos",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 14,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    productId: 14,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4800,
    booleanValue: null,
  },
  {
    productId: 14,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 40,
    booleanValue: null,
  },
  {
    productId: 15,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "iOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 15,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.1,
    booleanValue: null,
  },
  {
    productId: 15,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "OLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 15,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 144,
    booleanValue: null,
  },
  {
    productId: 15,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 15,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 6,
    booleanValue: null,
  },
  {
    productId: 15,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4200,
    booleanValue: null,
  },
  {
    productId: 15,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 150,
    booleanValue: null,
  },
  {
    productId: 16,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "iOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 16,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.1,
    booleanValue: null,
  },
  {
    productId: 16,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 16,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 16,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Exynos",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 16,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    productId: 16,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5500,
    booleanValue: null,
  },
  {
    productId: 16,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 64,
    booleanValue: null,
  },
  {
    productId: 17,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "iOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 17,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.0,
    booleanValue: null,
  },
  {
    productId: 17,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "LTPO",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 17,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 60,
    booleanValue: null,
  },
  {
    productId: 17,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 17,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    productId: 17,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 3800,
    booleanValue: null,
  },
  {
    productId: 17,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 50,
    booleanValue: null,
  },
  {
    productId: 18,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 18,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.1,
    booleanValue: null,
  },
  {
    productId: 18,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "LTPO",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 18,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 90,
    booleanValue: null,
  },
  {
    productId: 18,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Dimensity",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 18,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    productId: 18,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 3950,
    booleanValue: null,
  },
  {
    productId: 18,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 60,
    booleanValue: null,
  },
  {
    productId: 19,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 19,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.5,
    booleanValue: null,
  },
  {
    productId: 19,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "LTPO",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 19,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 60,
    booleanValue: null,
  },
  {
    productId: 19,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 19,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    productId: 19,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 6000,
    booleanValue: null,
  },
  {
    productId: 19,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 100,
    booleanValue: null,
  },
  {
    productId: 20,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "iOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 20,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.9,
    booleanValue: null,
  },
  {
    productId: 20,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "IPS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 20,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 20,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 20,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    productId: 20,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5200,
    booleanValue: null,
  },
  {
    productId: 20,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "number",
    unit: "MP",
    stringValue: null,
    numericValue: 50,
    booleanValue: null,
  },
];

// Định nghĩa kiểu dữ liệu cho việc tạo VariantSpecValue
interface VariantSpecValueSeedInput {
  variantId: number;
  specKey: string;
  label: string | null;
  type: DataType;
  unit: string | null;
  stringValue: string | null;
  numericValue: number | null;
  booleanValue: boolean | null;
}

// Map để chuyển từ specKey sang label tiếng Việt
const specKeyToLabelMapv: Record<string, string> = {
  ram_variant: "RAM",
  storage_variant: "Dung lượng lưu trữ",
  color_variant: "Màu sắc", // Thêm màu sắc nếu có
};

// Dữ liệu đã được xử lý và làm sạch
const variantSpecValuesToCreate: VariantSpecValueSeedInput[] = [
  {
    variantId: 1,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 1,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 2,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    variantId: 2,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 3,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    variantId: 3,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 4,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 4,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 5,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    variantId: 5,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 6,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 6,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 7,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 7,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 8,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 8,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 9,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 9,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 10,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 10,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 11,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 11,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 12,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 12,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 13,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    variantId: 13,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 14,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 14,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 15,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 15,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 16,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 16,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 17,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    variantId: 17,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 18,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 18,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 19,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    variantId: 19,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 20,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 20,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 21,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 21,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 22,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    variantId: 22,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 23,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    variantId: 23,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 24,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 128,
    booleanValue: null,
  },
  {
    variantId: 25,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 26,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 27,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 28,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 29,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 30,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue:null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 31,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 32,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 33,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 34,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 35,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue:null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 36,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 128,
    booleanValue: null,
  },
  {
    variantId: 37,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 128,
    booleanValue: null,
  },
  {
    variantId: 38,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue:null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 39,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 128,
    booleanValue: null,
  },
  {
    variantId: 40,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 41,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
];
