import { ControlType, DataType, Prisma, ValueType } from "@prisma/client";

// ---------------------------
// 1. DỮ LIỆU DANH MỤC (CATEGORIES)
// ---------------------------
export const categories: Prisma.CategoryCreateInput[] = [
  {
    name: "Điện thoại",
    slug: "dien-thoai",
  },
  {
    name: "Laptop",
    slug: "laptop",
  },
];

// ---------------------------
// 2. DỮ LIỆU THƯƠNG HIỆU (BRANDS)
// ---------------------------
export const brands: Prisma.BrandCreateInput[] = [
  // Điện thoại & Laptop
  {
    name: "Apple",
    slug: "apple",
  },
  {
    name: "Samsung",
    slug: "samsung",
  },
  {
    name: "Realme",
    slug: "realme",
  },
  {
    name: "Xiaomi",
    slug: "xiaomi",
  },
  {
    name: "Nokia",
    slug: "nokia",
  },
  {
    name: "OPPO",
    slug: "oppo",
  },
  {
    name: "Dell",
    slug: "dell",
  },
  {
    name: "Acer",
    slug: "acer",
  },
  {
    name: "HP",
    slug: "hp",
  },
  {
    name: "Lenovo",
    slug: "lenovo",
  },
];

// ---------------------------
// 3. DỮ LIỆU TEMPLATE THÔNG SỐ (SPEC TEMPLATES)
// ---------------------------
export const specTemplates: Prisma.SpecTemplateCreateInput[] = [
  {
    name: "Điện thoại - V1",
    version: 1,
    isActive: true,
    category: {
      connect: {
        slug: "dien-thoai",
      },
    },
  },
  {
    name: "Laptop - V1",
    version: 1,
    isActive: true,
    category: {
      connect: {
        slug: "laptop",
      },
    },
  },
];

// Định nghĩa kiểu dữ liệu đơn giản hóa cho việc tạo ProductSpec bằng ID trực tiếp
interface ProductSpecSeedInput {
  specTemplateId: number;
  code: string;
  label: string;
  valueType: ValueType;
  datatype: DataType;
  unit: string | null;
  filterable: boolean;
  control: ControlType;
  isRequired: boolean;
  groupLabel: string | null;
  displayOrder: number;
}

// =================================================================
// 4. DỮ LIỆU THÔNG SỐ SẢN PHẨM (PRODUCT SPECS)
// CHÚ Ý: Đã loại bỏ trường 'id' và dùng 'specTemplateId' trực tiếp.
// =================================================================
export const productSpecs: ProductSpecSeedInput[] = [
  // --- Specs cho SpecTemplate ID: 1 (Điện thoại - V1) ---
  {
    //1
    specTemplateId: 1,
    code: "os",
    label: "Hệ điều hành",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Cấu hình",
    displayOrder: 1,
  },
  {
    //2
    specTemplateId: 1,
    code: "screen_size",
    label: "Kích thước màn hình",
    valueType: "range",
    datatype: "number",
    unit: "inch",
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 2,
  },
  {
    //3
    specTemplateId: 1,
    code: "screen_tech",
    label: "Công nghệ màn hình",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 3,
  },
  {
    //4
    specTemplateId: 1,
    code: "refresh_rate",
    label: "Tần số quét",
    valueType: "range",
    datatype: "number",
    unit: "Hz",
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 4,
  },
  {
    //5
    specTemplateId: 1,
    code: "cpu_model",
    label: "Chip xử lý",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Hiệu năng",
    displayOrder: 5,
  },
  {
    //6
    specTemplateId: 1,
    code: "chipset",
    label: "Chipset",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: false,
    control: "select",
    isRequired: true,
    groupLabel: "Hiệu năng",
    displayOrder: 6,
  },
  {
    //7
    specTemplateId: 1,
    code: "ram",
    label: "RAM",
    valueType: "range",
    datatype: "number",
    unit: "GB",
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Hiệu năng",
    displayOrder: 6,
  },
  {
    //8
    specTemplateId: 1,
    code: "battery",
    label: "Dung lượng pin",
    valueType: "range",
    datatype: "number",
    unit: "mAh",
    filterable: true,
    control: "multiselect",
    isRequired: true,
    groupLabel: "Pin & Sạc",
    displayOrder: 7,
  },
  {
    //9
    specTemplateId: 1,
    code: "rear_camera_mp",
    label: "Camera sau",
    valueType: "discrete",
    datatype: "number",
    unit: "MP",
    filterable: false,
    control: "multiselect",
    isRequired: false,
    groupLabel: "Camera",
    displayOrder: 8,
  },
  {
    //10
    specTemplateId: 1,
    code: "nfc",
    label: "Công nghệ NFC",
    valueType: "discrete",
    datatype: "boolean",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: null,
    displayOrder: 9,
  },

  // --- Specs cho SpecTemplate ID: 2 (Laptop - V1) ---
  {
    //11
    specTemplateId: 2,
    code: "os",
    label: "Hệ điều hành",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Hệ điều hành",
    displayOrder: 1,
  },
  {
    //12
    specTemplateId: 2,
    code: "cpu_model",
    label: "CPU",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "multiselect",
    isRequired: false,
    groupLabel: "CPU",
    displayOrder: 2,
  },
  {
    //13
    specTemplateId: 2,
    code: "storage_type",
    label: "Chuẩn lưu trữ",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Bộ nhớ",
    displayOrder: 3,
  },
  {
    //14
    specTemplateId: 2,
    code: "gpu_model",
    label: "Model GPU",
    valueType: "discrete",
    datatype: "string",
    unit: null,
    filterable: false,
    control: "select",
    isRequired: false,
    groupLabel: "Đồ họa",
    displayOrder: 4,
  },
  {
    //15
    specTemplateId: 2,
    code: "screen_size",
    label: "Kích thước màn hình",
    valueType: "range",
    datatype: "number",
    unit: "inch",
    filterable: true,
    control: "select",
    isRequired: false,
    groupLabel: "Màn hình",
    displayOrder: 5,
  },
];

// Định nghĩa kiểu dữ liệu đơn giản hóa cho ProductSpecOption
interface ProductSpecOptionSeedInput {
  productSpecId: number;
  value: string;
  label: string;
  sortOrder: number;
}

// =================================================================
// 5. DỮ LIỆU TÙY CHỌN THÔNG SỐ (PRODUCT SPEC OPTIONS)
// CHÚ Ý: Đã loại bỏ trường 'id' và dùng 'productSpecId' trực tiếp.
// =================================================================
export const productSpecOptions: ProductSpecOptionSeedInput[] = [
  // --- Cho productSpecId: 1 (Hệ điều hành - Điện thoại) ---
  { productSpecId: 1, value: "Android", label: "Android", sortOrder: 0 },
  { productSpecId: 1, value: "iOS", label: "iOS", sortOrder: 1 },

  // --- Cho productSpecId: 3 (Công nghệ màn hình) ---
  { productSpecId: 3, value: "AMOLED", label: "AMOLED", sortOrder: 0 },
  { productSpecId: 3, value: "OLED", label: "OLED", sortOrder: 1 },
  { productSpecId: 3, value: "IPS", label: "IPS", sortOrder: 2 },
  { productSpecId: 3, value: "LTPO", label: "LTPO", sortOrder: 3 },

  // --- Cho productSpecId: 5 (Chip xử lý - Điện thoại) ---
  { productSpecId: 5, value: "Apple A", label: "Apple A", sortOrder: 0 },
  { productSpecId: 5, value: "Snapdragon", label: "Snapdragon", sortOrder: 1 },
  { productSpecId: 5, value: "Dimensity", label: "Dimensity", sortOrder: 2 },
  { productSpecId: 5, value: "Exynos", label: "Exynos", sortOrder: 3 },

  { productSpecId: 10, value: "true", label: "Có", sortOrder: 0 },
  { productSpecId: 10, value: "false", label: "Không", sortOrder: 1 },

  // --- Cho productSpecId: 10 (Hệ điều hành - Laptop) ---
  { productSpecId: 11, value: "Windows", label: "Windows", sortOrder: 0 },
  { productSpecId: 11, value: "macOS", label: "macOS", sortOrder: 1 },
  { productSpecId: 11, value: "Linux", label: "Linux", sortOrder: 2 },

  // --- Cho productSpecId: 12 (CPU - Laptop) ---
  { productSpecId: 12, value: "Core i5", label: "Intel Core i5", sortOrder: 0 },
  { productSpecId: 12, value: "Core i7", label: "Intel Core i7", sortOrder: 1 },
  { productSpecId: 12, value: "Ryzen 5", label: "AMD Ryzen 5", sortOrder: 2 },
  { productSpecId: 12, value: "Ryzen 7", label: "AMD Ryzen 7", sortOrder: 3 },
  { productSpecId: 12, value: "M2", label: "Apple M2", sortOrder: 4 },
  { productSpecId: 12, value: "M3", label: "Apple M3", sortOrder: 5 },

  // --- Cho productSpecId: 15 (Chuẩn lưu trữ) ---
  { productSpecId: 13, value: "SSD", label: "SSD", sortOrder: 0 },
  { productSpecId: 13, value: "HDD", label: "HDD", sortOrder: 1 },
];

// Định nghĩa kiểu dữ liệu đơn giản hóa cho ProductBucket
interface ProductBucketSeedInput {
  productSpecId: number;
  gt: string | null; // Sử dụng string hoặc null để seed giá trị Decimal
  lte: string | null; // Sử dụng string hoặc null để seed giá trị Decimal
  label: string;
  sortOrder: number;
}

// =================================================================
// 6. DỮ LIỆU KHOẢNG GIÁ TRỊ (PRODUCT BUCKETS)
// =================================================================
export const productBuckets: ProductBucketSeedInput[] = [
  // --- Cho productSpecId: 2 (Kích thước màn hình - Điện thoại, đơn vị ") ---
  {
    productSpecId: 2,
    gt: null,
    lte: "6.1",
    label: '< 6.1"',
    sortOrder: 0,
  },
  {
    productSpecId: 2,
    gt: "6.1",
    lte: "6.7",
    label: '6.1" - 6.7"',
    sortOrder: 1,
  },
  {
    productSpecId: 2,
    gt: "6.7",
    lte: null,
    label: '> 6.7"',
    sortOrder: 2,
  },

  // --- Cho productSpecId: 4 (Tần số quét - Điện thoại, đơn vị Hz) ---
  {
    productSpecId: 4,
    gt: null,
    lte: "60",
    label: "< 60Hz",
    sortOrder: 0,
  },
  {
    productSpecId: 4,
    gt: "60",
    lte: "90",
    label: "60–90Hz",
    sortOrder: 1,
  },
  {
    productSpecId: 4,
    gt: "90",
    lte: "120",
    label: "90–120Hz",
    sortOrder: 2,
  },
  {
    productSpecId: 4,
    gt: "120",
    lte: null,
    label: "> 120Hz",
    sortOrder: 3,
  },

  // --- Cho productSpecId: 6 (RAM - Điện thoại, đơn vị GB) ---
  {
    productSpecId: 7,
    gt: null,
    lte: "6",
    label: "< 6GB",
    sortOrder: 0,
  },
  {
    productSpecId: 7,
    gt: "6",
    lte: "8",
    label: "6–8GB",
    sortOrder: 1,
  },
  {
    productSpecId: 7,
    gt: "8",
    lte: "12",
    label: "8–12GB",
    sortOrder: 2,
  },
  {
    productSpecId: 7,
    gt: "12",
    lte: null,
    label: "> 12GB",
    sortOrder: 3,
  },

  // --- Cho productSpecId: 8 (Dung lượng pin - Điện thoại, đơn vị mAh) ---
  {
    productSpecId: 8,
    gt: null,
    lte: "4000",
    label: "< 4000mAh",
    sortOrder: 0,
  },
  {
    productSpecId: 8,
    gt: "4000",
    lte: "5000",
    label: "4000–5000mAh",
    sortOrder: 1,
  },
  {
    productSpecId: 8,
    gt: "5000",
    lte: null,
    label: "> 5000mAh",
    sortOrder: 2,
  },

  // --- Cho productSpecId: 9 (Camera sau - Điện thoại, đơn vị MP) ---
  {
    productSpecId: 9,
    gt: null,
    lte: "48",
    label: "< 48MP",
    sortOrder: 0,
  },
  {
    productSpecId: 9,
    gt: "48",
    lte: "64",
    label: "48–64MP",
    sortOrder: 1,
  },
  {
    productSpecId: 9,
    gt: "64",
    lte: "108",
    label: "64–108MP",
    sortOrder: 2,
  },
  {
    productSpecId: 9,
    gt: "108",
    lte: null,
    label: "> 108MP",
    sortOrder: 3,
  },

  // --- Cho productSpecId: 18 (Kích thước màn hình - Laptop, đơn vị ") ---
  {
    productSpecId: 15,
    gt: null,
    lte: "13",
    label: '< 13"',
    sortOrder: 0,
  },
  {
    productSpecId: 15,
    gt: "13",
    lte: "14",
    label: '13"–14"',
    sortOrder: 1,
  },
  {
    productSpecId: 15,
    gt: "14",
    lte: "15",
    label: '14" - 15"',
    sortOrder: 2,
  },
  {
    productSpecId: 15,
    gt: "15",
    lte: null,
    label: '> 15"',
    sortOrder: 3,
  },
];

interface VariantSpecSeedInput {
  specTemplateId: number;
  code: string;
  label: string;
  valueType: ValueType;
  datatype: DataType;
  unit: string | null;
  filterable: boolean;
  control: ControlType;
  isRequired: boolean;
  isVariantKey: boolean;
  orderIndex: number;
  groupLabel: string | null;
  displayOrder: number;
}

interface VariantSpecOptionSeedInput {
  variantSpecId: number;
  value: string;
  label: string;
  sortOrder: number;
}

// =================================================================
// 2. DỮ LIỆU THÔNG SỐ BIẾN THỂ (VARIANT SPECS)
// =================================================================
export const variantSpecs: VariantSpecSeedInput[] = [
  // specTemplateId: 1 (Điện thoại)
  {
    specTemplateId: 1,
    code: "storage_variant",
    label: "Dung lượng lưu trữ",
    valueType: ValueType.range,
    datatype: DataType.number,
    unit: "GB",
    filterable: true,
    control: ControlType.multiselect,
    isRequired: false,
    isVariantKey: true,
    orderIndex: 2,
    groupLabel: null,
    displayOrder: 2,
  },

  // specTemplateId: 2 (Laptop)
  {
    specTemplateId: 2,
    code: "ram_variant",
    label: "RAM",
    valueType: ValueType.discrete,
    datatype: DataType.number,
    unit: "GB",
    filterable: true,
    control: ControlType.select,
    isRequired: false,
    isVariantKey: true,
    orderIndex: 2,
    groupLabel: null,
    displayOrder: 2,
  },
  {
    specTemplateId: 2,
    code: "storage_variant",
    label: "Dung lượng lưu trữ",
    valueType: ValueType.range,
    datatype: DataType.number,
    unit: "GB",
    filterable: true,
    control: ControlType.multiselect,
    isRequired: false,
    isVariantKey: true,
    orderIndex: 3,
    groupLabel: null,
    displayOrder: 3,
  },
];

// =================================================================
// 3. DỮ LIỆU TÙY CHỌN THÔNG SỐ BIẾN THỂ (VARIANT SPEC OPTIONS)
// =================================================================
export const variantSpecOptions: VariantSpecOptionSeedInput[] = [
  // Dựa trên variantSpecId: 4
  { variantSpecId: 2, value: "8", label: "8GB", sortOrder: 0 },
  { variantSpecId: 2, value: "16", label: "16GB", sortOrder: 1 },
  { variantSpecId: 2, value: "32", label: "32GB", sortOrder: 2 },
];

// Định nghĩa kiểu dữ liệu đơn giản hóa cho VariantBucket
interface VariantBucketSeedInput {
  variantSpecId: number;
  gt: string | null; // Sử dụng string hoặc null
  lte: string | null; // Sử dụng string hoặc null
  label: string;
  sortOrder: number;
}

// =================================================================
// 8. DỮ LIỆU KHOẢNG GIÁ TRỊ BIẾN THỂ (VARIANT BUCKETS)
// CHÚ Ý: DÙNG ID CỨNG (variantSpecId: 2 và 5)
// =================================================================
export const variantBuckets: VariantBucketSeedInput[] = [
  // --- Cho variantSpecId: 2 (storage_variant của Điện thoại - Giả định) ---
  {
    variantSpecId: 1,
    gt: null,
    lte: "128",
    label: "< 128GB",
    sortOrder: 0,
  },
  {
    variantSpecId: 1,
    gt: "128",
    lte: "256",
    label: "128GB - 256GB",
    sortOrder: 1,
  },
  {
    variantSpecId: 1,
    gt: "256",
    lte: "512",
    label: "256GB - 512GB",
    sortOrder: 2,
  },
  {
    variantSpecId: 1,
    gt: "512",
    lte: null,
    label: "> 512GB",
    sortOrder: 3,
  },

  // --- Cho variantSpecId: 5 (storage_variant của Laptop - Giả định) ---
  {
    variantSpecId: 3,
    gt: null,
    lte: "512",
    label: "< 512GB",
    sortOrder: 0,
  },
  {
    variantSpecId: 3,
    gt: "512",
    lte: "1024",
    label: "512GB - 1TB",
    sortOrder: 1,
  },
  {
    variantSpecId: 3,
    gt: "1024",
    lte: null,
    label: "> 1TB",
    sortOrder: 2,
  },
];

// Định nghĩa kiểu dữ liệu cho việc tạo Product
// Loại bỏ 'id' và 'createdAt' vì DB sẽ tự quản lý
interface ProductSeedInput {
  name: string;
  slug: string;
  brandId: number;
  categoryId: number;
  description: string;
  ratingAvg?: number;
  ratingCount?: number;
  isActive?: boolean;
}

// Dữ liệu Product bạn đã cung cấp
export const productsToCreate: ProductSeedInput[] = [
  {
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    brandId: 2,
    categoryId: 1,
    description:
      "Samsung Galaxy S25 Ultra mạnh mẽ với chip Snapdragon 8 Elite For Galaxy mới nhất, RAM 12GB và bộ nhớ trong 256GB-1TB. Hệ thống 3 camera sau chất lượng gồm camera chính 200MP, camera tele 50MP và camera góc siêu rộng 50MP. Thiết kế kính cường lực Corning Gorilla Armor 2 và khung viền Titanium, màn hình Dynamic AMOLED 6.9 inch. Điện thoại này còn có viên pin 5000mAh, hỗ trợ 5G và Galaxy AI ấn tượng, nâng cao trải nghiệm người dùng!",
  },
  {
    name: "Samsung Galaxy Z Fold7",
    slug: "samsung-galaxy-z-fold7",
    brandId: 2,
    categoryId: 1,
    description:
      "Điện thoại Samsung Z Fold 7 mới đánh dấu bước tiến mạnh mẽ với thiết kế mỏng hơn, màn hình lớn hơn và vi xử lý thế hệ mới mạnh mẽ. Ngoài ra, các tính năng AI thông minh cùng camera 200MP cũng khiến mẫu smartphone của Samsung này trở nên thu hút hơn bao giờ hết. ",
  },
  {
    name: "Samsung Galaxy S24 Plus",
    slug: "samsung-galaxy-s24-plus",
    brandId: 2,
    categoryId: 1,
    description:
      "Samsung Galaxy S24+ 5G không chỉ tiếp nối thành công của người tiền nhiệm mà còn vươn lên một tầm cao mới với những nâng cấp vượt trội. Nhờ những nâng cấp này, Galaxy S24 Plus tiếp tục khẳng định vị thế của một flagship cao cấp trên thị trường.",
  },
  {
    name: "iPhone 17 Pro Max",
    slug: "iphone-17-pro-max",
    brandId: 1,
    categoryId: 1,
    description:
      'iPhone 17 Pro Max là phiên bản "xịn xò" nhất của thế hệ iPhone 17 series, được Apple trang bị những công nghệ hàng đầu về màn hình, hiệu năng và camera. Với ngoại hình hoàn toàn mới cùng nhiều nâng cấp về phần cứng lẫn tính năng, sản phẩm mang đến sức mạnh vượt trội, đáp ứng trọn vẹn từ nhu cầu sử dụng hằng ngày cho đến trải nghiệm chuyên nghiệp.',
  },
  {
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    brandId: 1,
    categoryId: 1,
    description:
      "iPhone 16 Pro Max sở hữu chipset A18 Pro mạnh mẽ giúp xử lý nhanh mọi tác vụ, camera 48 MP zoom quang 5x cho ảnh nét, màn hình 6.9 inch sống động. Pin dung lượng cao của máy hỗ trợ phát video tới 33 tiếng, đáp ứng nhu cầu giải trí liên tục suốt ngày dài. Cùng với đó là thiết kế khung Titanium bền nhẹ, mang lại cảm giác sang trọng và chắc chắn khi cầm.",
  },
  {
    name: "iPhone Air",
    slug: "iphone-air",
    brandId: 1,
    categoryId: 1,
    description:
      "iPhone Air là mẫu điện thoại mới của Apple, được người dùng đánh giá cao nhờ sở hữu màn hình Super Retina XDR 6,5 inch tần số quét ProMotion 120Hz. Thế hệ iPhone này sử dụng chip A19 Pro, hỗ trợ Apple Intelligence và kết nối Wi-Fi 7. Với khung Titanium cùng độ dày chỉ 5,6 mm, nó mang đến trải nghiệm vừa thời thượng vừa hiệu năng cao.",
  },
  {
    name: "realme 10",
    slug: "realme-10",
    brandId: 3,
    categoryId: 1,
    description:
      "realme 10 là sản phẩm mới tiếp theo mà realme sở hữu một thiết kế sang trọng cùng cấu hình mạnh mẽ. Cụ thể, điện thoại realme 10 được trang bị màn hình 6.4 inch với tấm nền Super AMOLED, tần số quét 90Hz mang lại hiển thị sống động, chuyển động mượt mà. Cấu hình điện thoại cũng ấn tượng với con chip Helio G99, bộ nhớ RAM lớn cùng viên pin 5000mAh cho thời gian sử dụng lâu dài.",
  },
  {
    name: "realme C61",
    slug: "realme-c61",
    brandId: 3,
    categoryId: 1,
    description:
      "Điện thoại realme C61 nổi bật với hiệu suất hoạt động ổn định và mượt mà cùng lúc nhiều tác vụ khác nhau nhờ trang bị chip UNISOC T612 cùng GPU Mali-G57. Kết hợp với RAM 4GB (Có thể mở rộng lên đến 8GB), bộ nhớ trong 128GB còn đem đến không gian lưu trữ dữ liệu đủ để đáp ứng các nhu cầu của người dùng. Bên cạnh đó, máy còn tích hợp bộ đôi camera gồm camera selfie 5MP và camera sau 50MP cho ảnh chụp sắc nét, rõ ràng. ",
  },
  {
    name: "Xiaomi 15 Ultra 5G",
    slug: "xiaomi-15-ultra-5g",
    brandId: 4,
    categoryId: 1,
    description:
      "Điện thoại Xiaomi 15 Ultra 5G 1TB với chip Snapdragon 8 Elite, 16GB RAM và bộ nhớ 1TB mang tới hiệu năng mạnh mẽ để phục vụ nhu cầu sử dụng nâng cao. Phiên bản Xiaomi 15 Series này sở hữu hệ thống camera Leica thế hệ mới để mở rộng khả năng sáng tạo. Hệ điều hành HyperOS 2 với tính năng AI sẽ giúp việc sử dụng điện thoại được tiện lợi hơn.",
  },
  {
    name: "Xiaomi 15 5G",
    slug: "xiaomi-15-5g",
    brandId: 4,
    categoryId: 1,
    description:
      "Xiaomi 15 sở hữu màn hình CrystalRes AMOLED 6.36 inch, độ phân giải 1200 x 2670 pixels, hỗ trợ 68 tỷ màu, công nghệ HDR10+ và tốc độ làm mới 120Hz. Máy sử dụng chip Qualcomm Snapdragon® 8 Elite siêu mạnh mẽ, RAM 12GB, bộ nhớ trong 256GB cùng pin 5240mAh. Bên cạnh đó, điện thoại Mi 15 còn hỗ trợ sạc nhanh 90W, camera sau gồm 3 ống kính 50MP, camera trước 32MP.",
  },
  {
    name: "Nokia 3210 4G",
    slug: "nokia-3210-4g",
    brandId: 5,
    categoryId: 1,
    description:
      "Nokia 3210 4G được trang bị màn hình 2.4 inch QVGA, hỗ trợ kết nối 4G LTE kết hợp pin dung lượng 1450mAh cho thời gian thoại tới vài ngày. Bộ nhớ trong của máy là 128MB. Điện thoại có camera sau 2MP và chạy trên nền tảng hệ điều hành S30+.",
  },
  {
    name: "OPPO FIND N5",
    slug: "oppo-find-n5",
    brandId: 6,
    categoryId: 1,
    description:
      "OPPO Find N5 được trang bị CPU Snapdragon 8 Elite mạnh nhất trong dòng điện thoại gập, tích hợp AI đến từ Qualcom cho hiệu năng vận hành mạnh mẽ mà vẫn tối ưu năng lượng tiêu hao. Sản phẩm sở hữu viên pin Silicone-carbon mỏng nhất thế giới, mang lại dung lượng cao 5600mAh. Cụm camera đảm bảo chất lượng ảnh, video được quay chụp sắc nét với màu sắc chân thực.",
  },
  {
    name: "OPPO Reno14 5G",
    slug: "oppo-reno14-5g",
    brandId: 6,
    categoryId: 1,
    description:
      "OPPO Reno 14 sở hữu màn hình FHD+ 6.59 inch, tần số quét 120Hz, mang đến hình ảnh sống động và sắc nét cho người dùng. Dung lượng pin của máy đạt tới 6000mAh, hỗ trợ sử dụng cả ngày dài mà không lo gián đoạn. Camera trước có độ phân giải 50MP, hỗ trợ quay video 4K, mang đến chất lượng hình ảnh rõ nét trong nhiều điều kiện ánh sáng.",
  },
  {
    name: "Laptop Dell Inspiron 14 5440 N4I7204W1",
    slug: "laptop-dell-inspiron-14-544-n4i7204w1",
    brandId: 7,
    categoryId: 2,
    description:
      "Laptop Dell Inspiron 14 5440 N4I7204W1 với chipset Intel Core i7 150U, 16GB RAM cùng ổ cứng 512GB hứa hẹn sẽ trở thành công cụ làm việc đáng tin cậy. Mẫu laptop Dell Inspiron này còn sở hữu màn hình FHD+ 14 inch 60Hz để đảm bảo hình ảnh luôn được hiển thị sắc nét. Kèm theo đó là viên pin có dung lượng 54WHr và đa dạng các cổng kết nối để đảm bảo công việc diễn ra ổn định.",
  },

  // {
  //   name: "",
  //   slug: "",
  //   brandId: 1,
  //   categoryId: 1,
  //   description: "",
  // },
];

// Định nghĩa kiểu dữ liệu cho việc tạo ProductSpecValue
// Đã loại bỏ 'id' và 'valueJson'
interface ProductSpecValueSeedInput {
  productId: number;
  specKey: string;
  label: string | null;
  type: DataType;
  unit: string | null;
  stringValue: string | null;
  numericValue: number | null;
  booleanValue: boolean | null;
}

// Map để chuyển từ specKey sang label tiếng Việt theo yêu cầu
const specKeyToLabelMap: Record<string, string> = {
  os: "Hệ điều hành",
  cpu_model: "Chip xử lý",
  storage_type: "Chuẩn lưu trữ",
  gpu_model: "Model GPU",
  chipset: "Chipset",
  screen_size: "Kích thước màn hình",
  screen_tech: "Công nghệ màn hình",
  refresh_rate: "Tần số quét",
  ram: "RAM",
  battery: "Dung lượng pin",
  rear_camera_mp: "Camera sau",
  nfc: "Công nghệ NFC",
};

// Dữ liệu đã được xử lý và làm sạch
export const productSpecValuesToCreate: ProductSpecValueSeedInput[] = [
  {
    productId: 1,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.9,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Dynamic AMOLED 2X",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon 8 Elite dành cho Galaxy (3nm)",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5000,
    booleanValue: null,
  },
  {
    productId: 1,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 2,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 8.0,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Dynamic AMOLED 2X",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon® 8 Elite 3nm for Galaxy",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: null,
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4400,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue: "200 MP, F1.7 + 12 MP, F2.2 + 10 MP, F2.4",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 2,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 3,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.7,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Dynamic AMOLED 2X",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Exynos",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Exynos 2400",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4900,
    booleanValue: null,
  },
  {
    productId: 3,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },

  {
    productId: 4,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "IOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.9,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Super Retina XDR OLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "A19 Pro",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4500,
    booleanValue: null,
  },

  {
    productId: 4,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 4,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 5,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "IOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.9,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Super Retina XDR OLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Apple A18 Pro",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 5,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },

  {
    productId: 5,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "IOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.5,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Super Retina XDR OLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Chip A19 Pro",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 6,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 7,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.4,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Super AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 90,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Helio",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Helio G99 (6nm)",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5000,
    booleanValue: null,
  },
  {
    productId: 7,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue: "Camera chính AI: 50MP, f/1.8\nCamera chân dung: 2MP, f/2.4",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.745,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "IPS LCD",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 90,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Unisoc Tiger",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Unisoc Tiger T612",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 6,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5000,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      'Camera góc rộng: 50 MP, ƒ/1.8, 1/2.5" Kích thước cảm biến\nỐng kính phụ trợ: 0.08 MP',
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 8,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: false,
  },
  {
    productId: 9,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Xiaomi HyperOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.73,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon 8 Elite (Tiến trình sản xuất 3nm) ",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5410,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      "Camera chính Leica: 50MP, ƒ/1.63, OIS\nCamera tele Leica: 50MP, ƒ/1.8, OIS\nCamera siêu tele Leica: 200MP, ƒ/2.6, OIS\nCamera góc siêu rộng Leica: 50MP, ƒ/2.2, 115° FOV",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 9,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 10,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Xiaomi HyperOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.36,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "CrystalRes AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon 8 Elite (Tiến trình sản xuất 3nm)",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5240,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      "Camera chính Leica: 50MP, ƒ/1.62, OIS, Tiêu cự tương đương 23mm\nCamera tele Leica: 50MP, ƒ/2.0, OIS\nCamera góc siêu rộng Leica: 50MP, ƒ/2.2, 115°",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 10,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 11,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 2.4,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Unisoc",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Unisoc T107",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 1450,
    booleanValue: null,
  },
  {
    productId: 11,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue: "2MP",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 8.12,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon® 8 Elite",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5600,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      "50MP, ƒ/1.8 OIS (Chính) + 8MP, ƒ/2.2 (Góc rộng) + 50MP, ƒ/2.7 (Tele)",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 12,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 13,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.59,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "MediaTek Dimensity",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "MediaTek Dimensity 8350 5G, tối đa 3.35GHz",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 6000,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      "Chính 50MP OIS, F/1.8\nTele 50MP OIS, F/2.8\nGóc rộng 8MP, F/2.2",
    numericValue: null,
    booleanValue: null,
  },
  {
    productId: 13,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },

  {
    productId: 14,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows",
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 14,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core 7",
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 14,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: true,
  },
  {
    productId: 14,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 14,
    booleanValue: true,
  },
];

interface VariantInterface {
  productId: number;
  color: string | null;

  // Sử dụng kiểu Decimal của Prisma cho giá trị tiền tệ chính xác
  price: number;
  compareAtPrice: number | null;

  stock: number;
  isActive: boolean;
  lowStockThreshold: number | null;
}

export const variant: VariantInterface[] = [
  {
    //1
    productId: 1,
    color: "Xám",
    price: 27480000,
    compareAtPrice: 33380000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    //2
    productId: 1,
    color: "Xám",
    price: 29480000,
    compareAtPrice: 36810000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    //3
    productId: 1,
    color: "Xám",
    price: 35490000,
    compareAtPrice: 43980000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 1,
    color: "Đen",
    price: 27480000,
    compareAtPrice: 33380000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 1,
    color: "Đen",
    price: 29480000,
    compareAtPrice: 36810000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 1,
    color: "Đen",
    price: 35490000,
    compareAtPrice: 43980000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 2,
    color: "Đen tuyền",
    price: 42990000,
    compareAtPrice: 46990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 2,
    color: "Đen tuyền",
    price: 46990000,
    compareAtPrice: 50990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 2,
    color: "Xám bóng",
    price: 42990000,
    compareAtPrice: 46990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 2,
    color: "Xám bóng",
    price: 46990000,
    compareAtPrice: 50990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 3,
    color: "Đen",
    price: 15790000,
    compareAtPrice: 18650000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 3,
    color: "Đen",
    price: 21190000,
    compareAtPrice: 29490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 3,
    color: "Tím",
    price: 15790000,
    compareAtPrice: 18650000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 3,
    color: "Tím",
    price: 21190000,
    compareAtPrice: 29490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Cam vũ trụ",
    price: 37990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Cam vũ trụ",
    price: 44490000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Cam vũ trụ",
    price: 50990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Cam vũ trụ",
    price: 63990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Bạc",
    price: 37990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Bạc",
    price: 44490000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Bạc",
    price: 50990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Bạc",
    price: 63990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Xanh đậm",
    price: 37990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Xanh đậm",
    price: 44490000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Xanh đậm",
    price: 50990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 4,
    color: "Xanh đậm",
    price: 63990000,
    compareAtPrice: null,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Đen",
    price: 30590000,
    compareAtPrice: 34990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Đen",
    price: 37190000,
    compareAtPrice: 40990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Đen",
    price: 42690000,
    compareAtPrice: 46990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Tự Nhiên",
    price: 30590000,
    compareAtPrice: 34990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Tự Nhiên",
    price: 37190000,
    compareAtPrice: 40990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Tự Nhiên",
    price: 42990000,
    compareAtPrice: 46990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Sa Mạc",
    price: 30290000,
    compareAtPrice: 34990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Sa Mạc",
    price: 36990000,
    compareAtPrice: 40990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Sa Mạc",
    price: 42690000,
    compareAtPrice: 46990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Trắng",
    price: 30590000,
    compareAtPrice: 34990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Trắng",
    price: 37190000,
    compareAtPrice: 40990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 5,
    color: "Titan Trắng",
    price: 42990000,
    compareAtPrice: 46990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 6,
    color: "Đen Không Gian",
    price: 29590000,
    compareAtPrice: 31990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 6,
    color: "Đen Không Gian",
    price: 37490000,
    compareAtPrice: 38490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 6,
    color: "Xanh Da Trời",
    price: 29990000,
    compareAtPrice: 31990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 6,
    color: "Xanh Da Trời",
    price: 37490000,
    compareAtPrice: 38490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 6,
    color: "Xanh Da Trời",
    price: 42490000,
    compareAtPrice: 44490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 7,
    color: "Đen",
    price: 7190000,
    compareAtPrice: 8290000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 7,
    color: "Trắng",
    price: 7190000,
    compareAtPrice: 8290000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 8,
    color: "Xanh",
    price: 2790000,
    compareAtPrice: 3990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 8,
    color: "Vàng",
    price: 2790000,
    compareAtPrice: 3990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 9,
    color: "Đen",
    price: 31990000,
    compareAtPrice: 34360000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 9,
    color: "Bạc",
    price: 31990000,
    compareAtPrice: 34360000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 9,
    color: "Bạc",
    price: 31990000,
    compareAtPrice: 38250000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 10,
    color: "Đen",
    price: 21290000,
    compareAtPrice: 24540000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 10,
    color: "Đen",
    price: 19490000,
    compareAtPrice: 26500000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 10,
    color: "Xanh lá",
    price: 20290000,
    compareAtPrice: 24540000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 10,
    color: "Xanh lá",
    price: 19490000,
    compareAtPrice: 26500000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 11,
    color: "Đen",
    price: 1480000,
    compareAtPrice: 1490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 11,
    color: "Vàng",
    price: 1480000,
    compareAtPrice: 1490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 11,
    color: "Xanh dương",
    price: 1480000,
    compareAtPrice: 1490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 12,
    color: "Trắng",
    price: 44180000,
    compareAtPrice: 44990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 12,
    color: "Đen",
    price: 44180000,
    compareAtPrice: 44990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 13,
    color: "Trắng",
    price: 15700000,
    compareAtPrice: 15990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 13,
    color: "Xanh lá",
    price: 15700000,
    compareAtPrice: 15990000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 3,
  },
  {
    productId: 14,
    color: "Xanh",
    price: 16690000,
    compareAtPrice: 20490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 2,
  },
  {
    productId: 14,
    color: "Xanh",
    price: 17490000,
    compareAtPrice: 21490000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 2,
  },
  {
    productId: 14,
    color: "Xanh",
    price: 18190000,
    compareAtPrice: 23590000,
    stock: 10,
    isActive: true,
    lowStockThreshold: 2,
  },
];

// Định nghĩa kiểu dữ liệu cho việc tạo VariantSpecValue
interface VariantSpecValueSeedInput {
  variantId: number;
  specKey: string;
  label: string | null;
  type: DataType;
  unit: string | null;
  stringValue: string | null;
  numericValue: number | null;
  booleanValue: boolean | null;
}

// Map để chuyển từ specKey sang label tiếng Việt
const specKeyToLabelMapv: Record<string, string> = {
  ram_variant: "RAM",
  storage_variant: "Dung lượng lưu trữ",
  color_variant: "Màu sắc", // Thêm màu sắc nếu có
};

// Dữ liệu đã được xử lý và làm sạch
export const variantSpecValuesToCreate: VariantSpecValueSeedInput[] = [
  {
    variantId: 1,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 2,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 3,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 4,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 5,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 6,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 7,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 8,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 9,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 10,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 11,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 12,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 13,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 14,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },

  {
    variantId: 15,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 16,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 17,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 18,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 19,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 20,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 21,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 22,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 23,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 24,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 25,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 26,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    variantId: 27,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 28,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 29,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 30,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 31,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 32,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 33,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 34,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 35,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 36,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 37,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 38,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 39,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 40,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 41,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 42,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 43,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 44,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 45,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 46,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 128,
    booleanValue: null,
  },
  {
    variantId: 47,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 128,
    booleanValue: null,
  },
  {
    variantId: 48,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 49,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 50,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    variantId: 51,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 52,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 53,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 54,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 58,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 59,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 60,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 61,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    variantId: 62,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 62,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    variantId: 62,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },

  {
    variantId: 63,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 63,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    variantId: 64,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    variantId: 64,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
];

// Định nghĩa interface cho đối tượng Media
interface MediaInterface {
  url: string;
  isPrimary: boolean;
  sortOrder: number;
}

export const MediaArray: MediaInterface[] = [
  {
    url: "dien-thoai-samsung-galaxy-s25-ultra_1__6.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-samsung-galaxy-s25-utra_7_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "dien-thoai-samsung-galaxy-s25-utra_5_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "dien-thoai-samsung-galaxy-s25-ultra_3__3.png",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-samsung-galaxy-s25-utra.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "dien-thoai-samsung-galaxy-s25-utra_1_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "samsung-galaxy-z-fold-7-den_2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "samsung-galaxy-z-fold-7-den-1.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "samsung-galaxy-z-fold-7-den-9.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "samsung-galaxy-z-fold-7-xam_2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "samsung-galaxy-z-fold-7-xam-1.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "samsung-galaxy-z-fold-7-xam-7.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "galaxy-s24-plus-den_2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "samsung-galaxy-s24_17__2.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "samsung-galaxy-s24_16__2.png",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "galaxy-s24-plus-tim_2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "samsung-galaxy-s24_9__2.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "samsung-galaxy-s24_8__2.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "samsung-galaxy-s24_10__2.webp",
    isPrimary: false,
    sortOrder: 4,
  },
  {
    url: "iphone-17-pro-max_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "1757455001441_thumb_3_iphone_17_pro_pro_max_didongviet.avif",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "1757455003231_thumb_4_iphone_17_pro_pro_max_didongviet.avif",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "iphone-17-pro-max-2_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "iphone-17-pro-max-silver-pdp-image-position-3-design-vn-vi.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "iphone-17-pro-max-silver-pdp-image-position-4-design-detail-vn-vi.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "iphone-17-pro-max-1_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "1757455173713_thumb_3_iphone_17_pro_pro_max_xanh_didongviet.avif",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "1757455175934_thumb_4_iphone_17_pro_pro_max_xanh_didongviet.avif",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "iphone-16-pro-max-titan-den.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "iphone-16-pro-max-den-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "iphone-16-pro-max-tu-nhien-1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "iphone-16-pro-max-tu-nhien-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "iphone-16-pro-max-sa-mac-1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "iphone-16-pro-max-sa-mac-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "iphone-16-pro-max-trang-1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "iphone-16-pro-max-trang-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "iphone-air-space-black-pdp-image-position-1-space-black-color-vn-vi.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "iphone-air-space-black-pdp-image-position-3-design-vn-vi.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "iphone-air-space-black-pdp-image-position-4-design-detail-vn-vi.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "iphone-air-sky-blue-pdp-image-position-1-sky-blue-color-vn-vi.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "iphone-air-sky-blue-pdp-image-position-3-design-vn-vi.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "iphone-air-sky-blue-pdp-image-position-4-design-detail-vn-vi.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "image-removebg-preview-9.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "image-removebg-preview-7.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "image-removebg-preview-4.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "image-removebg-preview-8.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "image-removebg-preview-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "image-removebg-preview-1.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "dien-thoai-realme-c61_2__2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "frame_133_2.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "frame_126_2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "frame_126_1.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "photo_2025-04-16_11-45-37_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "photo_2025-04-16_11-46-01.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "photo_2025-04-16_11-45-57.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "dien-thoai-xiaomi-15-ultra_17_.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-xiaomi-15-ultra_7_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "dien-thoai-xiaomi-15-ultra_9_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "dien-thoai-xiaomi-15_25_.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-xiaomi-15_21_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "dien-thoai-xiaomi-15_23_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "image_97__1_2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-xiaomi-15_15_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "dien-thoai-xiaomi-15_18_.webp",
    isPrimary: false,
    sortOrder: 3,
  },

  {
    url: "nokia-3210-4g.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "nokia-3210-4g_1_.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "nokia-3210-4g_2_.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "photo_2025-03-21_10-27-36.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-oppo-find-n5_h_nh_3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "dien-thoai-oppo-find-n5_h_nh_4.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    url: "photo_2025-03-21_10-27-52_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-oppo-find-n5_h_nh_8.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "dien-thoai-oppo-reno14-w_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-oppo-reno14_2.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "oppo-reno14-g.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "dien-thoai-oppo-reno14_8_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "text_ng_n_29__9_9.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    url: "text_ng_n_25__7_12.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    url: "text_ng_n_24__3_12.webp",
    isPrimary: false,
    sortOrder: 3,
  },
];

export interface MediaVariantInterface {
  mediaId: number;
  variantId: number;
}

export const MediaVariant: MediaVariantInterface[] = [
  { mediaId: 1, variantId: 1 },
  { mediaId: 1, variantId: 2 },
  { mediaId: 1, variantId: 3 },
  { mediaId: 2, variantId: 1 },
  { mediaId: 2, variantId: 2 },
  { mediaId: 2, variantId: 3 },
  { mediaId: 3, variantId: 1 },
  { mediaId: 3, variantId: 2 },
  { mediaId: 3, variantId: 3 },
  { mediaId: 4, variantId: 4 },
  { mediaId: 4, variantId: 5 },
  { mediaId: 4, variantId: 6 },
  { mediaId: 5, variantId: 4 },
  { mediaId: 5, variantId: 5 },
  { mediaId: 5, variantId: 6 },
  { mediaId: 6, variantId: 4 },
  { mediaId: 6, variantId: 5 },
  { mediaId: 6, variantId: 6 },
  { mediaId: 7, variantId: 7 },
  { mediaId: 7, variantId: 8 },
  { mediaId: 8, variantId: 7 },
  { mediaId: 8, variantId: 8 },
  { mediaId: 9, variantId: 7 },
  { mediaId: 9, variantId: 8 },
  { mediaId: 10, variantId: 9 },
  { mediaId: 10, variantId: 10 },
  { mediaId: 11, variantId: 9 },
  { mediaId: 11, variantId: 10 },
  { mediaId: 12, variantId: 9 },
  { mediaId: 12, variantId: 10 },
  { mediaId: 13, variantId: 11 },
  { mediaId: 13, variantId: 12 },
  { mediaId: 14, variantId: 11 },
  { mediaId: 14, variantId: 12 },
  { mediaId: 15, variantId: 11 },
  { mediaId: 15, variantId: 12 },
  { mediaId: 16, variantId: 13 },
  { mediaId: 16, variantId: 14 },
  { mediaId: 17, variantId: 13 },
  { mediaId: 17, variantId: 14 },
  { mediaId: 18, variantId: 13 },
  { mediaId: 18, variantId: 14 },
  { mediaId: 19, variantId: 13 },
  { mediaId: 19, variantId: 14 },
  { mediaId: 20, variantId: 15 },
  { mediaId: 20, variantId: 16 },
  { mediaId: 20, variantId: 17 },
  { mediaId: 20, variantId: 18 },
  { mediaId: 21, variantId: 15 },
  { mediaId: 21, variantId: 16 },
  { mediaId: 21, variantId: 17 },
  { mediaId: 21, variantId: 18 },
  { mediaId: 22, variantId: 15 },
  { mediaId: 22, variantId: 16 },
  { mediaId: 22, variantId: 17 },
  { mediaId: 22, variantId: 18 },
  { mediaId: 23, variantId: 19 },
  { mediaId: 23, variantId: 20 },
  { mediaId: 23, variantId: 21 },
  { mediaId: 23, variantId: 22 },
  { mediaId: 24, variantId: 19 },
  { mediaId: 24, variantId: 20 },
  { mediaId: 24, variantId: 21 },
  { mediaId: 24, variantId: 22 },
  { mediaId: 25, variantId: 19 },
  { mediaId: 25, variantId: 20 },
  { mediaId: 25, variantId: 21 },
  { mediaId: 25, variantId: 22 },
  { mediaId: 26, variantId: 23 },
  { mediaId: 26, variantId: 24 },
  { mediaId: 26, variantId: 25 },
  { mediaId: 26, variantId: 26 },
  { mediaId: 27, variantId: 23 },
  { mediaId: 27, variantId: 24 },
  { mediaId: 27, variantId: 25 },
  { mediaId: 27, variantId: 26 },
  { mediaId: 28, variantId: 23 },
  { mediaId: 28, variantId: 24 },
  { mediaId: 28, variantId: 25 },
  { mediaId: 28, variantId: 26 },
  { mediaId: 29, variantId: 27 },
  { mediaId: 29, variantId: 28 },
  { mediaId: 29, variantId: 29 },
  { mediaId: 30, variantId: 27 },
  { mediaId: 30, variantId: 28 },
  { mediaId: 30, variantId: 29 },
  { mediaId: 31, variantId: 30 },
  { mediaId: 31, variantId: 31 },
  { mediaId: 31, variantId: 32 },
  { mediaId: 32, variantId: 30 },
  { mediaId: 32, variantId: 31 },
  { mediaId: 32, variantId: 32 },
  { mediaId: 33, variantId: 33 },
  { mediaId: 33, variantId: 34 },
  { mediaId: 33, variantId: 35 },
  { mediaId: 34, variantId: 33 },
  { mediaId: 34, variantId: 34 },
  { mediaId: 34, variantId: 35 },
  { mediaId: 35, variantId: 36 },
  { mediaId: 35, variantId: 37 },
  { mediaId: 35, variantId: 38 },
  { mediaId: 36, variantId: 36 },
  { mediaId: 36, variantId: 37 },
  { mediaId: 36, variantId: 38 },
  { mediaId: 37, variantId: 39 },
  { mediaId: 37, variantId: 40 },
  { mediaId: 38, variantId: 39 },
  { mediaId: 38, variantId: 40 },
  { mediaId: 39, variantId: 39 },
  { mediaId: 39, variantId: 40 },
  { mediaId: 40, variantId: 41 },
  { mediaId: 40, variantId: 42 },
  { mediaId: 40, variantId: 43 },
  { mediaId: 41, variantId: 41 },
  { mediaId: 41, variantId: 42 },
  { mediaId: 41, variantId: 43 },
  { mediaId: 42, variantId: 41 },
  { mediaId: 42, variantId: 42 },
  { mediaId: 42, variantId: 43 },
  { mediaId: 43, variantId: 44 },
  { mediaId: 44, variantId: 44 },
  { mediaId: 45, variantId: 44 },
  { mediaId: 46, variantId: 45 },
  { mediaId: 47, variantId: 45 },
  { mediaId: 48, variantId: 45 },
  { mediaId: 49, variantId: 46 },
  { mediaId: 50, variantId: 46 },
  { mediaId: 51, variantId: 47 },
  { mediaId: 52, variantId: 47 },
  { mediaId: 53, variantId: 49 },
  { mediaId: 53, variantId: 50 },
  { mediaId: 54, variantId: 49 },
  { mediaId: 54, variantId: 50 },
  { mediaId: 55, variantId: 49 },
  { mediaId: 55, variantId: 50 },
  { mediaId: 56, variantId: 48 },
  { mediaId: 57, variantId: 48 },
  { mediaId: 58, variantId: 48 },
  { mediaId: 59, variantId: 51 },
  { mediaId: 59, variantId: 52 },
  { mediaId: 60, variantId: 51 },
  { mediaId: 60, variantId: 52 },
  { mediaId: 61, variantId: 51 },
  { mediaId: 61, variantId: 52 },
  { mediaId: 62, variantId: 53 },
  { mediaId: 62, variantId: 54 },
  { mediaId: 63, variantId: 53 },
  { mediaId: 63, variantId: 54 },
  { mediaId: 64, variantId: 53 },
  { mediaId: 64, variantId: 54 },
  { mediaId: 65, variantId: 55 },
  { mediaId: 67, variantId: 56 },
  { mediaId: 66, variantId: 57 },
  { mediaId: 71, variantId: 58 },
  { mediaId: 72, variantId: 58 },
  { mediaId: 68, variantId: 59 },
  { mediaId: 69, variantId: 59 },
  { mediaId: 70, variantId: 59 },
  { mediaId: 73, variantId: 60 },
  { mediaId: 74, variantId: 60 },
  { mediaId: 75, variantId: 61 },
  { mediaId: 76, variantId: 61 },
  { mediaId: 77, variantId: 62 },
  { mediaId: 77, variantId: 63 },
  { mediaId: 77, variantId: 64 },
  { mediaId: 78, variantId: 62 },
  { mediaId: 78, variantId: 63 },
  { mediaId: 78, variantId: 64 },
  { mediaId: 79, variantId: 62 },
  { mediaId: 79, variantId: 63 },
  { mediaId: 79, variantId: 64 },
];
