import './globals.css'

import { Inter } from "next/font/google"; // hoặc Roboto, Poppins...

const inter = Inter({
  subsets: ["latin", "latin-ext", "vietnamese"], // nhớ thêm "vietnamese"
  weight: ["400", "500", "700"],                 // chọn weights cần dùng
  variable: "--font-sans",                       // dùng kèm Tailwind/biến CSS
  display: "swap",                               // tránh chớp chữ
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="vi" className={inter.variable}>
      <body>{children}</body>
    </html>
  );
}
