const specKeyToLabelMap: Record<string, string> = {
  os: "Hệ điều hành",
  cpu_model: "Chip xử lý",
  storage_type: "Chuẩn lưu trữ",
  gpu_model: "Model GPU",
  chipset: "Chipset",
  screen_size: "Kích thước màn hình",
  screen_tech: "Công nghệ màn hình",
  refresh_rate: "Tần số quét",
  ram: "RAM",
  battery: "Dung lượng pin",
  rear_camera_mp: "Camera sau",
  nfc: "Công nghệ NFC",
  micro: "Micro",
  battery_life: "Thời lượng pin",
  input_port: "Cổng sạc vào",
  output_port: "Cổng sạc ra",
};

export const productSpecValues = [
  {
    id: 1,
    productId: 1,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 2,
    productId: 1,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.9,
    booleanValue: null,
  },
  {
    id: 3,
    productId: 1,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Dynamic AMOLED 2X",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 4,
    productId: 1,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 5,
    productId: 1,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 6,
    productId: 1,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon 8 Elite dành cho Galaxy (3nm)",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 7,
    productId: 1,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    id: 8,
    productId: 1,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5000,
    booleanValue: null,
  },
  {
    id: 9,
    productId: 1,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 10,
    productId: 2,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 11,
    productId: 2,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 8.0,
    booleanValue: null,
  },
  {
    id: 12,
    productId: 2,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Dynamic AMOLED 2X",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 13,
    productId: 2,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 14,
    productId: 2,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 15,
    productId: 2,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon® 8 Elite 3nm for Galaxy",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 16,
    productId: 2,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: null,
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    id: 17,
    productId: 2,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4400,
    booleanValue: null,
  },
  {
    id: 18,
    productId: 2,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue: "200 MP, F1.7 + 12 MP, F2.2 + 10 MP, F2.4",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 19,
    productId: 2,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 20,
    productId: 3,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 21,
    productId: 3,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.7,
    booleanValue: null,
  },
  {
    id: 22,
    productId: 3,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Dynamic AMOLED 2X",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 23,
    productId: 3,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 24,
    productId: 3,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Exynos",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 25,
    productId: 3,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Exynos 2400",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 26,
    productId: 3,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    id: 27,
    productId: 3,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4900,
    booleanValue: null,
  },
  {
    id: 28,
    productId: 3,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },

  {
    id: 29,
    productId: 4,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "IOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 30,
    productId: 4,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.9,
    booleanValue: null,
  },
  {
    id: 31,
    productId: 4,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Super Retina XDR OLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 32,
    productId: 4,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 33,
    productId: 4,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "A19 Pro",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 34,
    productId: 4,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    id: 35,
    productId: 4,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 4500,
    booleanValue: null,
  },

  {
    id: 36,
    productId: 4,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 37,
    productId: 4,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 38,
    productId: 5,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "IOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 39,
    productId: 5,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.9,
    booleanValue: null,
  },
  {
    id: 40,
    productId: 5,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Super Retina XDR OLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 41,
    productId: 5,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 42,
    productId: 5,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Apple A18 Pro",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 43,
    productId: 5,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },

  {
    id: 44,
    productId: 5,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 45,
    productId: 6,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "IOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 46,
    productId: 6,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.5,
    booleanValue: null,
  },
  {
    id: 47,
    productId: 6,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Super Retina XDR OLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 48,
    productId: 6,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 49,
    productId: 6,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Apple A",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 50,
    productId: 6,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Chip A19 Pro",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 51,
    productId: 6,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 52,
    productId: 7,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 53,
    productId: 7,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.4,
    booleanValue: null,
  },
  {
    id: 54,
    productId: 7,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "Super AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 55,
    productId: 7,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 90,
    booleanValue: null,
  },
  {
    id: 56,
    productId: 7,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Helio",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 57,
    productId: 7,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Helio G99 (6nm)",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 58,
    productId: 7,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    id: 59,
    productId: 7,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5000,
    booleanValue: null,
  },
  {
    id: 60,
    productId: 7,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue: "Camera chính AI: 50MP, f/1.8\nCamera chân dung: 2MP, f/2.4",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 61,
    productId: 8,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 62,
    productId: 8,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.745,
    booleanValue: null,
  },
  {
    id: 63,
    productId: 8,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "IPS LCD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 64,
    productId: 8,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 90,
    booleanValue: null,
  },
  {
    id: 65,
    productId: 8,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Unisoc Tiger",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 66,
    productId: 8,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Unisoc Tiger T612",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 67,
    productId: 8,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 6,
    booleanValue: null,
  },
  {
    id: 68,
    productId: 8,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5000,
    booleanValue: null,
  },
  {
    id: 69,
    productId: 8,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      'Camera góc rộng: 50 MP, ƒ/1.8, 1/2.5" Kích thước cảm biến\nỐng kính phụ trợ: 0.08 MP',
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 70,
    productId: 8,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: false,
  },
  {
    id: 71,
    productId: 9,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Xiaomi HyperOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 72,
    productId: 9,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.73,
    booleanValue: null,
  },
  {
    id: 73,
    productId: 9,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 74,
    productId: 9,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 75,
    productId: 9,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 76,
    productId: 9,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon 8 Elite (Tiến trình sản xuất 3nm) ",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 77,
    productId: 9,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    id: 78,
    productId: 9,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5410,
    booleanValue: null,
  },
  {
    id: 79,
    productId: 9,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      "Camera chính Leica: 50MP, ƒ/1.63, OIS\nCamera tele Leica: 50MP, ƒ/1.8, OIS\nCamera siêu tele Leica: 200MP, ƒ/2.6, OIS\nCamera góc siêu rộng Leica: 50MP, ƒ/2.2, 115° FOV",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 80,
    productId: 9,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 81,
    productId: 10,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Xiaomi HyperOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 82,
    productId: 10,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.36,
    booleanValue: null,
  },
  {
    id: 83,
    productId: 10,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "CrystalRes AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 84,
    productId: 10,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 85,
    productId: 10,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 86,
    productId: 10,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon 8 Elite (Tiến trình sản xuất 3nm)",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 87,
    productId: 10,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    id: 88,
    productId: 10,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5240,
    booleanValue: null,
  },
  {
    id: 89,
    productId: 10,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      "Camera chính Leica: 50MP, ƒ/1.62, OIS, Tiêu cự tương đương 23mm\nCamera tele Leica: 50MP, ƒ/2.0, OIS\nCamera góc siêu rộng Leica: 50MP, ƒ/2.2, 115°",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 90,
    productId: 10,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 91,
    productId: 11,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 2.4,
    booleanValue: null,
  },
  {
    id: 92,
    productId: 11,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Unisoc",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 93,
    productId: 11,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Unisoc T107",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 94,
    productId: 11,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 1450,
    booleanValue: null,
  },
  {
    id: 95,
    productId: 11,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue: "2MP",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 96,
    productId: 12,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 97,
    productId: 12,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 8.12,
    booleanValue: null,
  },
  {
    id: 98,
    productId: 12,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 99,
    productId: 12,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 100,
    productId: 12,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Snapdragon",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 101,
    productId: 12,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "Snapdragon® 8 Elite",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 102,
    productId: 12,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    id: 103,
    productId: 12,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 5600,
    booleanValue: null,
  },
  {
    id: 104,
    productId: 12,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      "50MP, ƒ/1.8 OIS (Chính) + 8MP, ƒ/2.2 (Góc rộng) + 50MP, ƒ/2.7 (Tele)",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 105,
    productId: 12,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 106,
    productId: 13,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Android",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 107,
    productId: 13,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 6.59,
    booleanValue: null,
  },
  {
    id: 108,
    productId: 13,
    specKey: "screen_tech",
    label: specKeyToLabelMap.screen_tech,
    type: "string",
    unit: null,
    stringValue: "AMOLED",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 109,
    productId: 13,
    specKey: "refresh_rate",
    label: specKeyToLabelMap.refresh_rate,
    type: "number",
    unit: "Hz",
    stringValue: null,
    numericValue: 120,
    booleanValue: null,
  },
  {
    id: 110,
    productId: 13,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "MediaTek Dimensity",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 111,
    productId: 13,
    specKey: "chipset",
    label: specKeyToLabelMap.chipset,
    type: "string",
    unit: null,
    stringValue: "MediaTek Dimensity 8350 5G, tối đa 3.35GHz",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 112,
    productId: 13,
    specKey: "ram",
    label: specKeyToLabelMap.ram,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 12,
    booleanValue: null,
  },
  {
    id: 113,
    productId: 13,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 6000,
    booleanValue: null,
  },
  {
    id: 114,
    productId: 13,
    specKey: "rear_camera_mp",
    label: specKeyToLabelMap.rear_camera_mp,
    type: "string",
    unit: null,
    stringValue:
      "Chính 50MP OIS, F/1.8\nTele 50MP OIS, F/2.8\nGóc rộng 8MP, F/2.2",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 115,
    productId: 13,
    specKey: "nfc",
    label: specKeyToLabelMap.nfc,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },

  {
    id: 116,
    productId: 14,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 117,
    productId: 14,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core 7",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 118,
    productId: 14,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 119,
    productId: 14,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 14,
    booleanValue: null,
  },
  {
    id: 120,
    productId: 15,
    specKey: "micro",
    label: specKeyToLabelMap.micro,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 121,
    productId: 15,
    specKey: "battery_life",
    label: specKeyToLabelMap.battery_life,
    type: "string",
    unit: null,
    stringValue: "Tai nghe: lên đến 8 giờ\nTai nghe + hộp sạc: lên đến 24 giờ",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 122,
    productId: 16,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "string",
    unit: "mAh",
    stringValue: null,
    numericValue: 10000,
    booleanValue: null,
  },
  {
    id: 123,
    productId: 16,
    specKey: "input_port",
    label: specKeyToLabelMap.input_port,
    type: "string",
    unit: null,
    stringValue: "1 x USB-C",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 124,
    productId: 16,
    specKey: "oputput_port",
    label: specKeyToLabelMap.oputput_port,
    type: "string",
    unit: null,
    stringValue: "1 x USB-C\n1 x cáp USB-C",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 125,
    productId: 17,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 126,
    productId: 17,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core Ultra 7 155H",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 127,
    productId: 17,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 128,
    productId: 17,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel ARC",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 129,
    productId: 17,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 13.4,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 130,
    productId: 18,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    stringValue: "Windows 11",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 131,
    productId: 18,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    stringValue: "Intel Core i7-13700H",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 132,
    productId: 18,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    stringValue: "SSD",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 133,
    productId: 18,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    stringValue: "NVIDIA RTX 4050",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 134,
    productId: 18,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 135,
    productId: 19,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    stringValue: "Windows 11",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 136,
    productId: 19,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    stringValue: "Intel Core i5-1340P",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 137,
    productId: 19,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    stringValue: "SSD",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 138,
    productId: 19,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    stringValue: "Intel Iris Xe",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 139,
    productId: 19,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 13.3,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 140,
    productId: 20,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    stringValue: "Windows 11",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 141,
    productId: 20,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    stringValue: "AMD Ryzen 7 7840HS",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 142,
    productId: 20,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    stringValue: "SSD",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 143,
    productId: 20,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    stringValue: "NVIDIA RTX 4060",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 144,
    productId: 20,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 145,
    productId: 21,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 146,
    productId: 21,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    stringValue: "Intel Core Ultra 9",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 147,
    productId: 21,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    stringValue: "SSD",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 148,
    productId: 21,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    stringValue: "Intel ARC",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 149,
    productId: 21,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 150,
    productId: 22,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 151,
    productId: 22,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    stringValue: "Intel Core i7-1360P",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 152,
    productId: 22,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    stringValue: "SSD",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 153,
    productId: 22,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    stringValue: "Intel Iris Xe",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 154,
    productId: 22,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 14,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 155,
    productId: 23,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    stringValue: "Windows 11 Pro",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 156,
    productId: 23,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    stringValue: "Intel Core Ultra 7",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 157,
    productId: 23,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    stringValue: "SSD",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 158,
    productId: 23,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    stringValue: "Intel ARC",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 159,
    productId: 23,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 14,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 160,
    productId: 24,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    numericValue: null,
    booleanValue: null,
    stringValue: "Windows 11",
    unit: null,
  },
  {
    id: 161,
    productId: 24,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    stringValue: "AMD Ryzen 5 7530U",
    numericValue: null,
    unit: null,
    booleanValue: null,
  },
  {
    id: 162,
    productId: 24,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 163,
    productId: 24,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    stringValue: "AMD Radeon Graphics",
    numericValue: null,
    booleanValue: null,
    unit: null,
  },
  {
    id: 164,
    productId: 24,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 165,
    productId: 25,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 166,
    productId: 25,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core i7-13620H",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 167,
    productId: 25,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 168,
    productId: 25,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Iris Xe",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 169,
    productId: 25,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 170,
    productId: 26,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11 Pro",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 171,
    productId: 26,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core i5-1345U",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 172,
    productId: 26,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 173,
    productId: 26,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Iris Xe",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 174,
    productId: 26,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 14,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 175,
    productId: 27,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 176,
    productId: 27,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "AMD Ryzen 5 5500U",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 177,
    productId: 27,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 178,
    productId: 27,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "NVIDIA GTX 1650",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 179,
    productId: 27,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 180,
    productId: 28,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 181,
    productId: 28,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core Ultra 5",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 182,
    productId: 28,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 183,
    productId: 28,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel ARC",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 184,
    productId: 28,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 14,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 185,
    productId: 29,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11 Home",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 186,
    productId: 29,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core i5-12450H",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 187,
    productId: 29,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 188,
    productId: 29,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel UHD Graphics",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 189,
    productId: 29,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 190,
    productId: 30,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 191,
    productId: 30,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core i7-13700HX",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 192,
    productId: 30,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 193,
    productId: 30,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "NVIDIA RTX 4070",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 194,
    productId: 30,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 195,
    productId: 31,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 196,
    productId: 31,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "AMD Ryzen 7 7840HS",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 197,
    productId: 31,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 198,
    productId: 31,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "NVIDIA RTX 4050",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 199,
    productId: 31,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 200,
    productId: 32,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 201,
    productId: 32,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core Ultra 5",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 202,
    productId: 32,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 203,
    productId: 32,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel ARC",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 204,
    productId: 32,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 14,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 205,
    productId: 33,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 206,
    productId: 33,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core i3-1215U",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 207,
    productId: 33,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 208,
    productId: 33,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel UHD Graphics",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 209,
    productId: 33,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 210,
    productId: 34,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "ChromeOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 211,
    productId: 34,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core i3-N305",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 212,
    productId: 34,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 213,
    productId: 34,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel UHD Graphics",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 214,
    productId: 34,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 215,
    productId: 35,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11 Pro",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 216,
    productId: 35,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel Core i5-1335U",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 217,
    productId: 35,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 218,
    productId: 35,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "Intel UHD Graphics",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 219,
    productId: 35,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 15.6,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 220,
    productId: 36,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "Windows 11",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 221,
    productId: 36,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "AMD Ryzen 9 7945HX",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 222,
    productId: 36,
    specKey: "storage_type",
    label: specKeyToLabelMap.storage_type,
    type: "string",
    unit: null,
    stringValue: "SSD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 223,
    productId: 36,
    specKey: "gpu_model",
    label: specKeyToLabelMap.gpu_model,
    type: "string",
    unit: null,
    stringValue: "NVIDIA RTX 4080",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 224,
    productId: 36,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 225,
    productId: 37,
    specKey: "micro",
    label: specKeyToLabelMap.micro,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 226,
    productId: 37,
    specKey: "battery_life",
    label: specKeyToLabelMap.battery_life,
    type: "string",
    unit: null,
    stringValue: "35 giờ (không ANC)",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 227,
    productId: 38,
    specKey: "micro",
    label: specKeyToLabelMap.micro,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 228,
    productId: 38,
    specKey: "battery_life",
    label: specKeyToLabelMap.battery_life,
    type: "string",
    unit: null,
    stringValue: "70 giờ (không ANC)",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 229,
    productId: 39,
    specKey: "micro",
    label: specKeyToLabelMap.micro,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 230,
    productId: 39,
    specKey: "battery_life",
    label: specKeyToLabelMap.battery_life,
    type: "string",
    unit: null,
    stringValue: "6 giờ (ANC on), 24 giờ kèm hộp",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 231,
    productId: 40,
    specKey: "micro",
    label: specKeyToLabelMap.micro,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 232,
    productId: 40,
    specKey: "battery_life",
    label: specKeyToLabelMap.battery_life,
    type: "string",
    unit: null,
    stringValue: "10 giờ (không ANC), 38 giờ kèm hộp",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 233,
    productId: 41,
    specKey: "micro",
    label: specKeyToLabelMap.micro,
    type: "boolean",
    unit: null,
    stringValue: null,
    numericValue: null,
    booleanValue: true,
  },
  {
    id: 234,
    productId: 41,
    specKey: "battery_life",
    label: specKeyToLabelMap.battery_life,
    type: "string",
    unit: null,
    stringValue: "5 giờ nghe nhạc, tổng 20 giờ với hộp",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 235,
    productId: 42,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 20000,
    booleanValue: null,
  },
  {
    id: 236,
    productId: 42,
    specKey: "input_port",
    label: specKeyToLabelMap.input_port,
    type: "string",
    unit: null,
    stringValue: "USB-C 18W",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 237,
    productId: 42,
    specKey: "oputput_port",
    label: specKeyToLabelMap.output_port,
    type: "string",
    unit: null,
    stringValue: "USB-A 22.5W, USB-C 22.5W",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 238,
    productId: 43,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 10000,
    booleanValue: null,
  },
  {
    id: 239,
    productId: 43,
    specKey: "input_port",
    label: specKeyToLabelMap.input_port,
    type: "string",
    unit: null,
    stringValue: "USB-C 25W PD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 240,
    productId: 43,
    specKey: "oputput_port",
    label: specKeyToLabelMap.output_port,
    type: "string",
    unit: null,
    stringValue: "USB-C 25W, USB-A 15W",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 241,
    productId: 44,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 20000,
    booleanValue: null,
  },
  {
    id: 242,
    productId: 44,
    specKey: "input_port",
    label: specKeyToLabelMap.input_port,
    type: "string",
    unit: null,
    stringValue: "Micro USB + USB-C",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 243,
    productId: 44,
    specKey: "oputput_port",
    label: specKeyToLabelMap.output_port,
    type: "string",
    unit: null,
    stringValue: "2 x USB-A",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 244,
    productId: 45,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 20000,
    booleanValue: null,
  },
  {
    id: 245,
    productId: 45,
    specKey: "input_port",
    label: specKeyToLabelMap.input_port,
    type: "string",
    unit: null,
    stringValue: "USB-C 30W PD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 246,
    productId: 45,
    specKey: "oputput_port",
    label: specKeyToLabelMap.output_port,
    type: "string",
    unit: null,
    stringValue: "USB-A 30W, USB-C 30W",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 247,
    productId: 46,
    specKey: "battery",
    label: specKeyToLabelMap.battery,
    type: "number",
    unit: "mAh",
    stringValue: null,
    numericValue: 10000,
    booleanValue: null,
  },
  {
    id: 248,
    productId: 46,
    specKey: "input_port",
    label: specKeyToLabelMap.input_port,
    type: "string",
    unit: null,
    stringValue: "USB-C 20W PD",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 249,
    productId: 46,
    specKey: "oputput_port",
    label: specKeyToLabelMap.output_port,
    type: "string",
    unit: null,
    stringValue: "USB-C 20W",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 250,
    productId: 47,
    specKey: "os",
    label: specKeyToLabelMap.os,
    type: "string",
    unit: null,
    stringValue: "macOS",
    numericValue: null,
    booleanValue: null,
  },
  {
    id: 251,
    productId: 47,
    specKey: "screen_size",
    label: specKeyToLabelMap.screen_size,
    type: "number",
    unit: "inch",
    stringValue: null,
    numericValue: 14.2,
    booleanValue: null,
  },
  {
    id: 252,
    productId: 47,
    specKey: "cpu_model",
    label: specKeyToLabelMap.cpu_model,
    type: "string",
    unit: null,
    stringValue: "Chip Apple M5",
    numericValue: null,
    booleanValue: null,
  },


];
