export const products = [
  {
    id: 1,
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    brandId: 2,
    categoryId: 1,
    description:
      "Samsung Galaxy S25 Ultra mạnh mẽ với chip Snapdragon 8 Elite For Galaxy mới nhất, RAM 12GB và bộ nhớ trong 256GB-1TB. Hệ thống 3 camera sau chất lượng gồm camera chính 200MP, camera tele 50MP và camera góc siêu rộng 50MP. Thiết kế kính cường lực Corning Gorilla Armor 2 và khung viền Titanium, màn hình Dynamic AMOLED 6.9 inch. Điện thoại này còn có viên pin 5000mAh, hỗ trợ 5G và Galaxy AI ấn tượng, nâng cao trải nghiệm người dùng!",
    warrantyMonths: 12,
  },
  {
    id: 2,
    name: "Samsung Galaxy Z Fold7",
    slug: "samsung-galaxy-z-fold7",
    brandId: 2,
    categoryId: 1,
    description:
      "Điện thoại Samsung Z Fold 7 mới đánh dấu bước tiến mạnh mẽ với thiết kế mỏng hơn, màn hình lớn hơn và vi xử lý thế hệ mới mạnh mẽ. Ngoài ra, các tính năng AI thông minh cùng camera 200MP cũng khiến mẫu smartphone của Samsung này trở nên thu hút hơn bao giờ hết. ",
    warrantyMonths: 12,
  },
  {
    id: 3,
    name: "Samsung Galaxy S24 Plus",
    slug: "samsung-galaxy-s24-plus",
    brandId: 2,
    categoryId: 1,
    description:
      "Samsung Galaxy S24+ 5G không chỉ tiếp nối thành công của người tiền nhiệm mà còn vươn lên một tầm cao mới với những nâng cấp vượt trội. Nhờ những nâng cấp này, Galaxy S24 Plus tiếp tục khẳng định vị thế của một flagship cao cấp trên thị trường.",
    warrantyMonths: 12,
  },
  {
    id: 4,
    name: "iPhone 17 Pro Max",
    slug: "iphone-17-pro-max",
    brandId: 1,
    categoryId: 1,
    description:
      'iPhone 17 Pro Max là phiên bản "xịn xò" nhất của thế hệ iPhone 17 series, được Apple trang bị những công nghệ hàng đầu về màn hình, hiệu năng và camera. Với ngoại hình hoàn toàn mới cùng nhiều nâng cấp về phần cứng lẫn tính năng, sản phẩm mang đến sức mạnh vượt trội, đáp ứng trọn vẹn từ nhu cầu sử dụng hằng ngày cho đến trải nghiệm chuyên nghiệp.',
    warrantyMonths: 12,
  },
  {
    id: 5,
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    brandId: 1,
    categoryId: 1,
    description:
      "iPhone 16 Pro Max sở hữu chipset A18 Pro mạnh mẽ giúp xử lý nhanh mọi tác vụ, camera 48 MP zoom quang 5x cho ảnh nét, màn hình 6.9 inch sống động. Pin dung lượng cao của máy hỗ trợ phát video tới 33 tiếng, đáp ứng nhu cầu giải trí liên tục suốt ngày dài. Cùng với đó là thiết kế khung Titanium bền nhẹ, mang lại cảm giác sang trọng và chắc chắn khi cầm.",
    warrantyMonths: 12,
  },
  {
    id: 6,
    name: "iPhone Air",
    slug: "iphone-air",
    brandId: 1,
    categoryId: 1,
    description:
      "iPhone Air là mẫu điện thoại mới của Apple, được người dùng đánh giá cao nhờ sở hữu màn hình Super Retina XDR 6,5 inch tần số quét ProMotion 120Hz. Thế hệ iPhone này sử dụng chip A19 Pro, hỗ trợ Apple Intelligence và kết nối Wi-Fi 7. Với khung Titanium cùng độ dày chỉ 5,6 mm, nó mang đến trải nghiệm vừa thời thượng vừa hiệu năng cao.",
    warrantyMonths: 12,
  },
  {
    id: 7,
    name: "realme 10",
    slug: "realme-10",
    brandId: 3,
    categoryId: 1,
    description:
      "realme 10 là sản phẩm mới tiếp theo mà realme sở hữu một thiết kế sang trọng cùng cấu hình mạnh mẽ. Cụ thể, điện thoại realme 10 được trang bị màn hình 6.4 inch với tấm nền Super AMOLED, tần số quét 90Hz mang lại hiển thị sống động, chuyển động mượt mà. Cấu hình điện thoại cũng ấn tượng với con chip Helio G99, bộ nhớ RAM lớn cùng viên pin 5000mAh cho thời gian sử dụng lâu dài.",
    warrantyMonths: 12,
  },
  {
    id: 8,
    name: "realme C61",
    slug: "realme-c61",
    brandId: 3,
    categoryId: 1,
    description:
      "Điện thoại realme C61 nổi bật với hiệu suất hoạt động ổn định và mượt mà cùng lúc nhiều tác vụ khác nhau nhờ trang bị chip UNISOC T612 cùng GPU Mali-G57. Kết hợp với RAM 4GB (Có thể mở rộng lên đến 8GB), bộ nhớ trong 128GB còn đem đến không gian lưu trữ dữ liệu đủ để đáp ứng các nhu cầu của người dùng. Bên cạnh đó, máy còn tích hợp bộ đôi camera gồm camera selfie 5MP và camera sau 50MP cho ảnh chụp sắc nét, rõ ràng. ",
    warrantyMonths: 12,
  },
  {
    id: 9,
    name: "Xiaomi 15 Ultra 5G",
    slug: "xiaomi-15-ultra-5g",
    brandId: 4,
    categoryId: 1,
    description:
      "Điện thoại Xiaomi 15 Ultra 5G 1TB với chip Snapdragon 8 Elite, 16GB RAM và bộ nhớ 1TB mang tới hiệu năng mạnh mẽ để phục vụ nhu cầu sử dụng nâng cao. Phiên bản Xiaomi 15 Series này sở hữu hệ thống camera Leica thế hệ mới để mở rộng khả năng sáng tạo. Hệ điều hành HyperOS 2 với tính năng AI sẽ giúp việc sử dụng điện thoại được tiện lợi hơn.",
    warrantyMonths: 12,
  },
  {
    id: 10,
    name: "Xiaomi 15 5G",
    slug: "xiaomi-15-5g",
    brandId: 4,
    categoryId: 1,
    description:
      "Xiaomi 15 sở hữu màn hình CrystalRes AMOLED 6.36 inch, độ phân giải 1200 x 2670 pixels, hỗ trợ 68 tỷ màu, công nghệ HDR10+ và tốc độ làm mới 120Hz. Máy sử dụng chip Qualcomm Snapdragon® 8 Elite siêu mạnh mẽ, RAM 12GB, bộ nhớ trong 256GB cùng pin 5240mAh. Bên cạnh đó, điện thoại Mi 15 còn hỗ trợ sạc nhanh 90W, camera sau gồm 3 ống kính 50MP, camera trước 32MP.",
    warrantyMonths: 12,
  },
  {
    id: 11,
    name: "Nokia 3210 4G",
    slug: "nokia-3210-4g",
    brandId: 5,
    categoryId: 1,
    description:
      "Nokia 3210 4G được trang bị màn hình 2.4 inch QVGA, hỗ trợ kết nối 4G LTE kết hợp pin dung lượng 1450mAh cho thời gian thoại tới vài ngày. Bộ nhớ trong của máy là 128MB. Điện thoại có camera sau 2MP và chạy trên nền tảng hệ điều hành S30+.",
    warrantyMonths: 12,
  },
  {
    id: 12,
    name: "OPPO FIND N5",
    slug: "oppo-find-n5",
    brandId: 6,
    categoryId: 1,
    description:
      "OPPO Find N5 được trang bị CPU Snapdragon 8 Elite mạnh nhất trong dòng điện thoại gập, tích hợp AI đến từ Qualcom cho hiệu năng vận hành mạnh mẽ mà vẫn tối ưu năng lượng tiêu hao. Sản phẩm sở hữu viên pin Silicone-carbon mỏng nhất thế giới, mang lại dung lượng cao 5600mAh. Cụm camera đảm bảo chất lượng ảnh, video được quay chụp sắc nét với màu sắc chân thực.",
    warrantyMonths: 12,
  },
  {
    id: 13,
    name: "OPPO Reno14 5G",
    slug: "oppo-reno14-5g",
    brandId: 6,
    categoryId: 1,
    description:
      "OPPO Reno 14 sở hữu màn hình FHD+ 6.59 inch, tần số quét 120Hz, mang đến hình ảnh sống động và sắc nét cho người dùng. Dung lượng pin của máy đạt tới 6000mAh, hỗ trợ sử dụng cả ngày dài mà không lo gián đoạn. Camera trước có độ phân giải 50MP, hỗ trợ quay video 4K, mang đến chất lượng hình ảnh rõ nét trong nhiều điều kiện ánh sáng.",
    warrantyMonths: 12,
  },
  {
    id: 14,
    name: "Laptop Dell Inspiron 14 5440 N4I7204W1",
    slug: "laptop-dell-inspiron-14-544-n4i7204w1",
    brandId: 7,
    categoryId: 2,
    description:
      "Laptop Dell Inspiron 14 5440 N4I7204W1 với chipset Intel Core i7 150U, 16GB RAM cùng ổ cứng 512GB hứa hẹn sẽ trở thành công cụ làm việc đáng tin cậy. Mẫu laptop Dell Inspiron này còn sở hữu màn hình FHD+ 14 inch 60Hz để đảm bảo hình ảnh luôn được hiển thị sắc nét. Kèm theo đó là viên pin có dung lượng 54WHr và đa dạng các cổng kết nối để đảm bảo công việc diễn ra ổn định.",
    warrantyMonths: 12,
  },
  {
    id: 15,
    name: "Tai nghe Bluetooth Apple AirPods Pro 3 2025 Type-C | Chính hãng (MFHP4ZP/A)",
    slug: "tai-nghe-bluetooth-apple-airpods-pro-3-2025-type-c-chinh-hang",
    brandId: 1,
    categoryId: 3,
    description:
      "AirPods Pro 3 ra mắt tháng 9/2025, mang đến bước tiến lớn với khả năng khử tiếng ồn chủ động gấp đôi thế hệ trước, thiết kế gọn nhẹ và pin bền bỉ vượt trội. Apple tích hợp cảm biến đo nhịp tim trực tiếp trên tai nghe, biến AirPod Pro 3 thành trợ lý sức khỏe thông minh cho người dùng. Cùng với chất lượng âm thanh ấn tượng, Airpods Pro 3 hứa hẹn nâng tầm trải nghiệm nghe nhạc và giao tiếp hàng ngày.",
    warrantyMonths: 6,
  },
  {
    id: 16,
    name: "Pin dự phòng Xiaomi 10.000mAh 165W tích hợp cáp Type-C",
    slug: "pin-du-phong-xiaomi-10000mAh-165w-tich-hop-cap-type-c",
    brandId: 4,
    categoryId: 4,
    description:
      "Pin sạc dự phòng Xiaomi 10000mAh 165W kèm cáp type C được trang bị dung lượng 10000mAh hỗ trợ sạc nhiều thiết bị cùng lúc hoặc sạc nhiều lần tiện lợi. Sản phẩm sạc dự phòng Xiaomi này sở hữu công suất tối đa đạt 165 Watt cho hiệu quả nạp pin nhanh chóng, đầy ấn tượng. Thiết kế cầm tay tiện lợi kèm cáp type C giúp việc sạc trở nên di động và đơn giản hơn.",
    warrantyMonths: 12,
  },
  {
    id: 17,
    name: "Laptop Dell XPS 13 9340",
    slug: "laptop-dell-xps-13-9340",
    brandId: 7,
    categoryId: 2,
    description:
      "Dell XPS 13 9340 trang bị Intel Core Ultra 7, RAM 16GB, SSD 512GB, màn hình OLED 13.4 inch sắc nét.",
  },
  {
    id: 18,
    name: "Laptop Dell XPS 15 9530",
    slug: "laptop-dell-xps-15-9530",
    brandId: 7,
    categoryId: 2,
    description:
      "Dell XPS 15 với chip Intel Core i7 thế hệ mới, GPU RTX 4050, phù hợp đồ hoạ và lập trình.",
  },
  {
    id: 19,
    name: "Laptop Acer Swift 3 OLED",
    slug: "laptop-acer-swift-3-oled",
    brandId: 8,
    categoryId: 2,
    description:
      "Acer Swift 3 OLED sử dụng chipset Intel Core i5, RAM 16GB, màn OLED 2.8K.",
  },
  {
    id: 20,
    name: "Laptop Acer Nitro 5 2024",
    slug: "laptop-acer-nitro-5-2024",
    brandId: 8,
    categoryId: 2,
    description:
      "Acer Nitro 5 mới với CPU Ryzen 7, RTX 4060, tối ưu cho gaming.",
  },
  {
    id: 21,
    name: "Laptop HP Envy 16 2024",
    slug: "laptop-hp-envy-16-2024",
    brandId: 9,
    categoryId: 2,
    description:
      "HP Envy 16 trang bị Intel Core Ultra 9, GPU Intel ARC, tản nhiệt nâng cấp.",
  },
  {
    id: 22,
    name: "Laptop HP Spectre x360 14",
    slug: "laptop-hp-spectre-x360-14",
    brandId: 9,
    categoryId: 2,
    description: "Spectre x360 thiết kế cao cấp, màn OLED 3K, xoay gập 360 độ.",
  },
  {
    id: 23,
    name: "Laptop Lenovo ThinkPad X1 Carbon Gen 12",
    slug: "laptop-thinkpad-x1-carbon-gen-12",
    brandId: 10,
    categoryId: 2,
    description: "ThinkPad X1 Carbon bền bỉ chuẩn quân đội, CPU Intel Gen 14.",
  },
  {
    id: 24,
    name: "Laptop Lenovo IdeaPad Slim 5",
    slug: "laptop-ideapad-slim-5",
    brandId: 10,
    categoryId: 2,
    description: "IdeaPad Slim 5 nhẹ, pin trâu, giá mềm cho sinh viên.",
  },
  {
    id: 25,
    name: "Laptop Dell Inspiron 15 5630",
    slug: "laptop-dell-inspiron-15-5630",
    brandId: 7,
    categoryId: 2,
    description:
      "Laptop Dell Inspiron mới với Core i7, RAM 16GB và màn hình 15.6 inch.",
  },
  {
    id: 26,
    name: "Laptop Dell Latitude 5440",
    slug: "laptop-dell-latitude-5440",
    brandId: 7,
    categoryId: 2,
    description: "Latitude 5440 dành cho doanh nghiệp, bảo mật cao, bền bỉ.",
  },
  {
    id: 27,
    name: "Laptop Acer Aspire 7",
    slug: "laptop-acer-aspire-7",
    brandId: 8,
    categoryId: 2,
    description:
      "Aspire 7 sử dụng Ryzen 5 + GTX 1650, phù hợp đồ hoạ nhẹ & coding.",
  },
  {
    id: 28,
    name: "Laptop Acer Swift Go 14",
    slug: "laptop-acer-swift-go-14",
    brandId: 8,
    categoryId: 2,
    description: "Swift Go 14 với màn OLED 2.8K, trọng lượng chỉ 1.2kg.",
  },
  {
    id: 29,
    name: "Laptop HP Pavilion 15",
    slug: "laptop-hp-pavilion-15",
    brandId: 9,
    categoryId: 2,
    description:
      "HP Pavilion 15 với Core i5, RAM 8GB phù hợp sinh viên & văn phòng.",
  },
  {
    id: 30,
    name: "Laptop HP Omen 16",
    slug: "laptop-hp-omen-16",
    brandId: 9,
    categoryId: 2,
    description: "HP Omen 16 mạnh mẽ với RTX 4070, giải pháp gaming cao cấp.",
  },
  {
    id: 31,
    name: "Laptop Lenovo LOQ 15",
    slug: "laptop-lenovo-loq-15",
    brandId: 10,
    categoryId: 2,
    description: "Lenovo LOQ 15 sử dụng Ryzen 7, RTX 4050 phù hợp eSports.",
  },
  {
    id: 32,
    name: "Laptop Lenovo Yoga Slim 7",
    slug: "laptop-lenovo-yoga-slim-7",
    brandId: 10,
    categoryId: 2,
    description: "Yoga Slim 7 mỏng nhẹ, chip Intel Ultra 5, màn hình cảm ứng.",
  },
  {
    id: 33,
    name: "Laptop Dell Vostro 3520",
    slug: "laptop-dell-vostro-3520",
    brandId: 7,
    categoryId: 2,
    description: "Dell Vostro 3520 hiệu năng ổn định, phù hợp văn phòng.",
  },
  {
    id: 34,
    name: "Laptop Acer Chromebook Plus 515",
    slug: "laptop-acer-chromebook-plus-515",
    brandId: 8,
    categoryId: 2,
    description: "Chromebook Plus với ChromeOS nhẹ, pin 12 giờ.",
  },
  {
    id: 35,
    name: "Laptop HP ProBook 450 G10",
    slug: "laptop-hp-probook-450-g10",
    brandId: 9,
    categoryId: 2,
    description: "HP ProBook dành cho doanh nghiệp, CPU Gen 14.",
  },
  {
    id: 36,
    name: "Laptop Lenovo Legion 7",
    slug: "laptop-lenovo-legion-7",
    brandId: 10,
    categoryId: 2,
    description: "Legion 7 gaming hiệu năng cao với RTX 4080.",
  },
  {
    id: 37,
    name: "Tai nghe Bluetooth Sony WH-CH720N",
    slug: "tai-nghe-sony-wh-ch720n",
    brandId: 11,
    categoryId: 3,
    description: "Sony WH-CH720N chống ồn tốt, pin 35 giờ.",
  },
  {
    id: 38,
    name: "Tai nghe JBL Tune 770NC",
    slug: "tai-nghe-jbl-tune-770nc",
    brandId: 11,
    categoryId: 3,
    description: "JBL Tune 770NC âm trầm mạnh, thời lượng pin 70 giờ.",
  },
  {
    id: 39,
    name: "Tai nghe Samsung Galaxy Buds 3",
    slug: "samsung-galaxy-buds-3",
    brandId: 2,
    categoryId: 3,
    description: "Galaxy Buds 3 với Ambient Sound và chống ồn chủ động.",
  },
  {
    id: 40,
    name: "Tai nghe Xiaomi Buds 5 Pro",
    slug: "xiaomi-buds-5-pro",
    brandId: 4,
    categoryId: 3,
    description: "Buds 5 Pro hỗ trợ LHDC và pin dài 38 giờ.",
  },
  {
    id: 41,
    name: "Tai nghe Lenovo LivePods LP6",
    slug: "lenovo-livepods-lp6",
    brandId: 10,
    categoryId: 3,
    description: "Tai nghe Lenovo LP6 giá rẻ, âm thanh mạnh mẽ.",
  },
  {
    id: 42,
    name: "Pin dự phòng Anker PowerCore 20.000mAh 22.5W",
    slug: "anker-powercore-20000-225w",
    brandId: 11,
    categoryId: 4,
    description: "Pin dự phòng Anker 20000mAh hỗ trợ sạc nhanh 22.5W.",
  },
  {
    id: 43,
    name: "Pin dự phòng Samsung 25W 10000mAh",
    slug: "samsung-10000mah-25w",
    brandId: 2,
    categoryId: 4,
    description: "Samsung 10000mAh sạc vào ra 25W chuẩn PD.",
  },
  {
    id: 44,
    name: "Pin dự phòng Xiaomi Redmi 20000mAh",
    slug: "xiaomi-redmi-20000mah",
    brandId: 4,
    categoryId: 4,
    description: "Redmi Power Bank 20.000mAh giá tốt, 2 cổng output.",
  },
  {
    id: 45,
    name: "Pin dự phòng Baseus Bipow Pro 20.000mAh 30W",
    slug: "baseus-bipow-pro-20000",
    brandId: 11,
    categoryId: 4,
    description: "Baseus Bipow Pro 30W hỗ trợ PD + QC 3.0.",
  },
  {
    id: 46,
    name: "Pin dự phòng Anker Nano Power Bank 10.000mAh",
    slug: "anker-nano-powerbank-10000",
    brandId: 11,
    categoryId: 4,
    description: "Anker Nano 10.000mAh nhỏ gọn kèm cáp Type-C.",
  },










  {
    id: 47,
    name: "MacBook Pro 14 M5",
    slug: "macbook-pro-14-m5",
    brandId: 1,
    categoryId: 2,
    description:
      "Macbook Pro 14 inch  là lựa chọn lý tưởng cho người dùng chuyên nghiệp đang tìm kiếm hiệu năng mạnh mẽ và khả năng tối ưu cao. Với cấu hình chip mới, thiết bị Macbook Pro chip M5 mang lại tốc độ xử lý nhanh hơn và khả năng đồ họa ấn tượng.",
    warrantyMonths: 24,
  },
];
