export const media = [
  {
    id: 1,
    url: "dien-thoai-samsung-galaxy-s25-ultra_1__6.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 2,
    url: "dien-thoai-samsung-galaxy-s25-utra_7_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 3,
    url: "dien-thoai-samsung-galaxy-s25-utra_5_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 4,
    url: "dien-thoai-samsung-galaxy-s25-ultra_3__3.png",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 5,
    url: "dien-thoai-samsung-galaxy-s25-utra.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 6,
    url: "dien-thoai-samsung-galaxy-s25-utra_1_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 7,
    url: "samsung-galaxy-z-fold-7-den_2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 8,
    url: "samsung-galaxy-z-fold-7-den-1.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 9,
    url: "samsung-galaxy-z-fold-7-den-9.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 10,
    url: "samsung-galaxy-z-fold-7-xam_2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 11,
    url: "samsung-galaxy-z-fold-7-xam-1.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 12,
    url: "samsung-galaxy-z-fold-7-xam-7.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  { id: 13, url: "galaxy-s24-plus-den_2.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 14,
    url: "samsung-galaxy-s24_17__2.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 15,
    url: "samsung-galaxy-s24_16__2.png",
    isPrimary: false,
    sortOrder: 3,
  },
  { id: 16, url: "galaxy-s24-plus-tim_2.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 17,
    url: "samsung-galaxy-s24_9__2.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 18,
    url: "samsung-galaxy-s24_8__2.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 19,
    url: "samsung-galaxy-s24_10__2.webp",
    isPrimary: false,
    sortOrder: 4,
  },
  { id: 20, url: "iphone-17-pro-max_1.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 21,
    url: "1757455001441_thumb_3_iphone_17_pro_pro_max_didongviet.avif",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 22,
    url: "1757455003231_thumb_4_iphone_17_pro_pro_max_didongviet.avif",
    isPrimary: false,
    sortOrder: 3,
  },
  { id: 23, url: "iphone-17-pro-max-2_1.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 24,
    url: "iphone-17-pro-max-silver-pdp-image-position-3-design-vn-vi.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 25,
    url: "iphone-17-pro-max-silver-pdp-image-position-4-design-detail-vn-vi.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  { id: 26, url: "iphone-17-pro-max-1_1.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 27,
    url: "1757455173713_thumb_3_iphone_17_pro_pro_max_xanh_didongviet.avif",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 28,
    url: "1757455175934_thumb_4_iphone_17_pro_pro_max_xanh_didongviet.avif",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 29,
    url: "iphone-16-pro-max-titan-den.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 30,
    url: "iphone-16-pro-max-den-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 31,
    url: "iphone-16-pro-max-tu-nhien-1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 32,
    url: "iphone-16-pro-max-tu-nhien-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 33,
    url: "iphone-16-pro-max-sa-mac-1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 34,
    url: "iphone-16-pro-max-sa-mac-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 35,
    url: "iphone-16-pro-max-trang-1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 36,
    url: "iphone-16-pro-max-trang-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 37,
    url: "iphone-air-space-black-pdp-image-position-1-space-black-color-vn-vi.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 38,
    url: "iphone-air-space-black-pdp-image-position-3-design-vn-vi.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 39,
    url: "iphone-air-space-black-pdp-image-position-4-design-detail-vn-vi.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 40,
    url: "iphone-air-sky-blue-pdp-image-position-1-sky-blue-color-vn-vi.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 41,
    url: "iphone-air-sky-blue-pdp-image-position-3-design-vn-vi.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 42,
    url: "iphone-air-sky-blue-pdp-image-position-4-design-detail-vn-vi.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 43,
    url: "image-removebg-preview-9.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 44,
    url: "image-removebg-preview-7.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 45,
    url: "image-removebg-preview-4.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 46,
    url: "image-removebg-preview-8.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 47,
    url: "image-removebg-preview-3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 48,
    url: "image-removebg-preview-1.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 49,
    url: "dien-thoai-realme-c61_2__2.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  { id: 50, url: "frame_133_2.webp", isPrimary: false, sortOrder: 2 },
  { id: 51, url: "frame_126_2.webp", isPrimary: true, sortOrder: 1 },
  { id: 52, url: "frame_126_1.webp", isPrimary: false, sortOrder: 2 },
  {
    id: 53,
    url: "photo_2025-04-16_11-45-37_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 54,
    url: "photo_2025-04-16_11-46-01.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 55,
    url: "photo_2025-04-16_11-45-57.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 56,
    url: "dien-thoai-xiaomi-15-ultra_17_.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 57,
    url: "dien-thoai-xiaomi-15-ultra_7_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 58,
    url: "dien-thoai-xiaomi-15-ultra_9_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 59,
    url: "dien-thoai-xiaomi-15_25_.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 60,
    url: "dien-thoai-xiaomi-15_21_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 61,
    url: "dien-thoai-xiaomi-15_23_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  { id: 62, url: "image_97__1_2.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 63,
    url: "dien-thoai-xiaomi-15_15_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 64,
    url: "dien-thoai-xiaomi-15_18_.webp",
    isPrimary: false,
    sortOrder: 3,
  },

  { id: 65, url: "nokia-3210-4g.webp", isPrimary: true, sortOrder: 1 },
  { id: 66, url: "nokia-3210-4g_1_.webp", isPrimary: true, sortOrder: 1 },
  { id: 67, url: "nokia-3210-4g_2_.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 68,
    url: "photo_2025-03-21_10-27-36.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 69,
    url: "dien-thoai-oppo-find-n5_h_nh_3.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 70,
    url: "dien-thoai-oppo-find-n5_h_nh_4.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 71,
    url: "photo_2025-03-21_10-27-52_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 72,
    url: "dien-thoai-oppo-find-n5_h_nh_8.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 73,
    url: "dien-thoai-oppo-reno14-w_1.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 74,
    url: "dien-thoai-oppo-reno14_2.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  { id: 75, url: "oppo-reno14-g.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 76,
    url: "dien-thoai-oppo-reno14_8_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  { id: 77, url: "text_ng_n_29__9_9.webp", isPrimary: true, sortOrder: 1 },
  { id: 78, url: "text_ng_n_25__7_12.webp", isPrimary: false, sortOrder: 2 },
  { id: 79, url: "text_ng_n_24__3_12.webp", isPrimary: false, sortOrder: 3 },
  { id: 80, url: "group_111_1_1.webp", isPrimary: true, sortOrder: 1 },
  {
    id: 81,
    url: "airpods_pro_3_sep25_pdp_image_position_1__vn-vi_1.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 82,
    url: "airpods_pro_3_sep25_pdp_image_position_3__vn-vi_1.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 83,
    url: "airpods_pro_3_sep25_pdp_image_position_4__vn-vi_1.webp",
    isPrimary: false,
    sortOrder: 4,
  },
  {
    id: 84,
    url: "airpods_pro_3_sep25_pdp_image_position_7__vn-vi_1.webp",
    isPrimary: false,
    sortOrder: 5,
  },
  {
    id: 85,
    url: "airpods_pro_3_sep25_pdp_image_position_8__vn-vi_1.webp",
    isPrimary: false,
    sortOrder: 6,
  },
  {
    id: 86,
    url: "pin-sac-du-phong-xiaomi-10000mah-165w-kem-cap-type-c_3.webp",
    isPrimary: true,
    sortOrder: 1,
  },
  {
    id: 87,
    url: "pin-sac-du-phong-xiaomi-10000mah-165w-kem-cap-type-c_3_.webp",
    isPrimary: false,
    sortOrder: 2,
  },
  {
    id: 88,
    url: "pin-sac-du-phong-xiaomi-10000mah-165w-kem-cap-type-c_2_.webp",
    isPrimary: false,
    sortOrder: 3,
  },
  {
    id: 89,
    url: "pin-sac-du-phong-xiaomi-10000mah-165w-kem-cap-type-c_9_.webp",
    isPrimary: false,
    sortOrder: 4,
  },
  {
    id: 90,
    url: "pin-sac-du-phong-xiaomi-10000mah-165w-kem-cap-type-c_8_.webp",
    isPrimary: false,
    sortOrder: 5,
  },
  { id: 91, url: "17x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 92, url: "17x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 93, url: "17x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 94, url: "18x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 95, url: "18x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 96, url: "18x3.webp", isPrimary: false, sortOrder: 3 },
  
  { id: 97, url: "19x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 98, url: "19x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 99, url: "19x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 100, url: "20x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 101, url: "20x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 102, url: "20x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 103, url: "21x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 104, url: "21x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 105, url: "21x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 106, url: "22x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 107, url: "22x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 108, url: "22x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 109, url: "23x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 110, url: "23x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 111, url: "23x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 112, url: "24x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 113, url: "24x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 114, url: "24x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 115, url: "25x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 116, url: "25x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 117, url: "25x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 118, url: "26x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 119, url: "26x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 120, url: "26x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 121, url: "27x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 122, url: "27x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 123, url: "27x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 124, url: "28x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 125, url: "28x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 126, url: "28x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 127, url: "29x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 128, url: "29x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 129, url: "29x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 130, url: "30x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 131, url: "30x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 132, url: "30x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 133, url: "31x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 134, url: "31x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 135, url: "31x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 136, url: "32x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 137, url: "32x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 138, url: "32x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 139, url: "33x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 140, url: "33x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 141, url: "33x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 142, url: "34x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 143, url: "34x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 144, url: "34x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 145, url: "35x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 146, url: "35x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 147, url: "35x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 148, url: "36x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 149, url: "36x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 150, url: "36x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 151, url: "37x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 152, url: "37x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 153, url: "37x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 154, url: "38x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 155, url: "38x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 156, url: "38x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 157, url: "39x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 158, url: "39x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 159, url: "39x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 160, url: "40x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 161, url: "40x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 162, url: "40x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 163, url: "41x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 164, url: "41x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 165, url: "41x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 166, url: "42x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 167, url: "42x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 168, url: "42x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 169, url: "43x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 170, url: "43x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 171, url: "43x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 172, url: "44x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 173, url: "44x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 174, url: "44x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 175, url: "45x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 176, url: "45x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 177, url: "45x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 178, url: "46x1.webp", isPrimary: true, sortOrder: 1 },
  { id: 179, url: "46x2.webp", isPrimary: false, sortOrder: 2 },
  { id: 180, url: "46x3.webp", isPrimary: false, sortOrder: 3 },
  { id: 181, url: "macbook_9__4.webp", isPrimary: true, sortOrder: 1 },
  { id: 182, url: "690x300_MacBookProM5_opensale.webp", isPrimary: false, sortOrder: 2 },
];
