// Map để chuyển từ specKey sang label tiếng Việt
const specKeyToLabelMapv: Record<string, string> = {
  ram_variant: "RAM",
  storage_variant: "Dung lượng lưu trữ",
  color_variant: "Màu sắc", // Thêm màu sắc nếu có
};

// Dữ liệu đã được xử lý và làm sạch
export const variantSpecValues = [
  {
    id: 1,
    variantId: 1,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 2,
    variantId: 2,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 3,
    variantId: 3,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 4,
    variantId: 4,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 5,
    variantId: 5,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 6,
    variantId: 6,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 7,
    variantId: 7,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 8,
    variantId: 8,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 9,
    variantId: 9,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 10,
    variantId: 10,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 11,
    variantId: 11,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 12,
    variantId: 12,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 13,
    variantId: 13,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 14,
    variantId: 14,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },

  {
    id: 15,
    variantId: 15,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 16,
    variantId: 16,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 17,
    variantId: 17,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 18,
    variantId: 18,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    id: 19,
    variantId: 19,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 20,
    variantId: 20,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 21,
    variantId: 21,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 22,
    variantId: 22,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    id: 23,
    variantId: 23,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 24,
    variantId: 24,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 25,
    variantId: 25,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 26,
    variantId: 26,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 2048,
    booleanValue: null,
  },
  {
    id: 27,
    variantId: 27,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 28,
    variantId: 28,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 29,
    variantId: 29,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 30,
    variantId: 30,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 31,
    variantId: 31,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 32,
    variantId: 32,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 33,
    variantId: 33,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 34,
    variantId: 34,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 35,
    variantId: 35,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 36,
    variantId: 36,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 37,
    variantId: 37,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 38,
    variantId: 38,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 39,
    variantId: 39,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 40,
    variantId: 40,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 41,
    variantId: 41,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 42,
    variantId: 42,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 43,
    variantId: 43,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 44,
    variantId: 44,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 45,
    variantId: 45,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 46,
    variantId: 46,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 128,
    booleanValue: null,
  },
  {
    id: 47,
    variantId: 47,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 128,
    booleanValue: null,
  },
  {
    id: 48,
    variantId: 48,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 49,
    variantId: 49,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 50,
    variantId: 50,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 51,
    variantId: 51,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 52,
    variantId: 52,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 53,
    variantId: 53,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 54,
    variantId: 54,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 55,
    variantId: 58,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 56,
    variantId: 59,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 57,
    variantId: 60,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 58,
    variantId: 61,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 256,
    booleanValue: null,
  },
  {
    id: 59,
    variantId: 62,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    id: 60,
    variantId: 62,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 8,
    booleanValue: null,
  },
  {
    id: 61,
    variantId: 62,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },

  {
    id: 62,
    variantId: 63,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    id: 63,
    variantId: 63,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },
  {
    id: 64,
    variantId: 64,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    id: 65,
    variantId: 64,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 66,
    variantId: 65,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    id: 67,
    variantId: 65,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 512,
    booleanValue: null,
  },

  {
    id: 68,
    variantId: 66,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    id: 69,
    variantId: 66,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 70,
    variantId: 67,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 71,
    variantId: 67,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 72,
    variantId: 68,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 73,
    variantId: 68,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 2048,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 74,
    variantId: 69,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 75,
    variantId: 69,
    specKey: "storage_variant",
    numericValue: 256,
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 76,
    variantId: 70,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 77,
    variantId: 70,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 78,
    variantId: 71,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 79,
    variantId: 71,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 80,
    variantId: 72,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 81,
    variantId: 72,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 82,
    variantId: 73,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 83,
    variantId: 73,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 84,
    variantId: 74,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 85,
    variantId: 74,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 2048,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 86,
    variantId: 75,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 87,
    variantId: 75,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 88,
    variantId: 76,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 89,
    variantId: 76,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 90,
    variantId: 77,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 91,
    variantId: 77,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 92,
    variantId: 78,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 93,
    variantId: 78,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 2048,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 94,
    variantId: 79,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 95,
    variantId: 79,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 256,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 96,
    variantId: 80,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 97,
    variantId: 80,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 98,
    variantId: 81,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 99,
    variantId: 81,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 100,
    variantId: 82,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 101,
    variantId: 82,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 102,
    variantId: 83,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 103,
    variantId: 83,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 256,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 104,
    variantId: 84,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 105,
    variantId: 84,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 106,
    variantId: 85,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 107,
    variantId: 85,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 256,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 108,
    variantId: 86,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 109,
    variantId: 86,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 110,
    variantId: 87,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 111,
    variantId: 87,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 112,
    variantId: 88,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 113,
    variantId: 88,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 114,
    variantId: 89,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 115,
    variantId: 89,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 256,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 116,
    variantId: 90,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 117,
    variantId: 90,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 118,
    variantId: 91,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 32,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 119,
    variantId: 91,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 120,
    variantId: 92,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 32,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 121,
    variantId: 92,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 2048,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 122,
    variantId: 93,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 123,
    variantId: 93,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 124,
    variantId: 94,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 125,
    variantId: 94,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 126,
    variantId: 95,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 127,
    variantId: 95,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 128,
    variantId: 96,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 129,
    variantId: 96,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 130,
    variantId: 97,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 131,
    variantId: 97,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 256,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 132,
    variantId: 98,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 133,
    variantId: 98,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 134,
    variantId: 99,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 135,
    variantId: 99,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 256,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 136,
    variantId: 100,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 8,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 137,
    variantId: 100,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 138,
    variantId: 101,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 139,
    variantId: 101,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 512,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 140,
    variantId: 102,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 16,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 141,
    variantId: 102,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 142,
    variantId: 103,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 32,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 143,
    variantId: 103,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 1024,
    stringValue: null,
    booleanValue: null,
  },

  {
    id: 144,
    variantId: 104,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    numericValue: 32,
    stringValue: null,
    booleanValue: null,
  },
  {
    id: 145,
    variantId: 104,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    numericValue: 2048,
    stringValue: null,
    booleanValue: null,
  },













  {
    id: 146,
    variantId: 122,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 16,
    booleanValue: null,
  },
  {
    id: 147,
    variantId: 122,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
  {
    id: 148,
    variantId: 123,
    specKey: "ram_variant",
    label: specKeyToLabelMapv.ram_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 32,
    booleanValue: null,
  },
  {
    id: 149,
    variantId: 123,
    specKey: "storage_variant",
    label: specKeyToLabelMapv.storage_variant,
    type: "number",
    unit: "GB",
    stringValue: null,
    numericValue: 1024,
    booleanValue: null,
  },
];
